#!/usr/bin/env python3
"""Seed script: imports existing report data into MySQL.

Run once after initial setup to populate the database with data
from the manually-compiled report.
"""

import sys
import logging
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from config import setup_logging, load_config
from db.connection import get_connection
from db import schema

_logger = logging.getLogger(__name__)


def seed():
    setup_logging()
    load_config()
    conn = get_connection()
    schema.init_schema(conn)

    _logger.info("Seeding database with existing report data...")

    # ── Failed Startups (Part 1A: US & Global) ──
    us_global = [
        (
            "Byju's",
            "EdTech",
            None,
            "US",
            "US & Global",
            5400000000,
            "~$5.4B+ (valued at $22B)",
            2011,
            2024,
            "Financial mismanagement, aggressive acquisition spree",
            None,
            1,
            "manual",
        ),
        (
            "Fisker",
            "EV/Automotive",
            "EV Manufacturing",
            "US",
            "US & Global",
            1000000000,
            "~$1B+",
            2016,
            2024,
            "Poor product quality, failed to compete with Tesla",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Bird",
            "Micro-mobility",
            None,
            "US",
            "US & Global",
            776000000,
            "~$776M (unicorn at $2.4B)",
            2017,
            2024,
            "Unit economics failure, regulatory issues",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "EasyKnock",
            "Proptech",
            None,
            "US",
            "US & Global",
            455000000,
            "$455M",
            2016,
            2024,
            "Market conditions, financial model unsustainability",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "Rad Power Bikes",
            "Mobility/EV",
            "E-bike Manufacturing",
            "US",
            "US & Global",
            300000000,
            "~$300M+",
            2015,
            2024,
            "Supply chain, cash flow issues",
            "supply_chain",
            1,
            "manual",
        ),
        (
            "Tally",
            "Fintech",
            None,
            "US",
            "US & Global",
            87000000,
            "~$87M",
            2015,
            2024,
            "Debt consolidation market challenges",
            "no_market_need",
            1,
            "manual",
        ),
        (
            "Northvolt",
            "Battery Manufacturing",
            "Battery Cell Manufacturing",
            "Sweden",
            "US & Global",
            14000000000,
            "$14B+",
            2016,
            2024,
            "Production delays, cost overruns, cancelled orders",
            "capital_intensity",
            1,
            "manual",
        ),
        (
            "Mindstrong",
            "Healthtech",
            None,
            "US",
            "US & Global",
            None,
            "Significant VC backing",
            2014,
            2024,
            "Business model issues in digital health",
            "no_business_model",
            1,
            "manual",
        ),
        (
            "Tessera",
            "Biotech/Genomics",
            None,
            "US",
            "US & Global",
            None,
            "Well-funded",
            2016,
            2024,
            "Technical/scientific challenges",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Veev",
            "PropTech/Construction",
            "Modular Construction",
            "US",
            "US & Global",
            600000000,
            "~$600M+",
            2014,
            2024,
            "Supply chain costs, market downturn in real estate",
            "supply_chain",
            1,
            "manual",
        ),
    ]

    # Manufacturing-specific failures
    mfg_failures = [
        (
            "Desktop Metal",
            "3D Printing",
            "3D Printing / Additive Mfg",
            "US",
            "US & Global",
            6000000000,
            "~$6B (SPAC valuation)",
            2010,
            2024,
            "SPAC overvaluation, inability to achieve profitability",
            "spac_overvaluation",
            0,
            "manual",
        ),
        (
            "BCN3D",
            "3D Printing",
            "3D Printing",
            "Spain",
            "Europe",
            None,
            "~€50M+ raised",
            2015,
            2025,
            "Voluntary bankruptcy; market oversaturation",
            "no_market_need",
            0,
            "manual",
        ),
        (
            "Black Buffalo 3D",
            "3D Printing",
            "Construction 3D Printing",
            "US",
            "US & Global",
            None,
            "Significant funding",
            2018,
            2025,
            "Chapter 11 bankruptcy; market failed to materialize",
            "market_timing",
            0,
            "manual",
        ),
        (
            "Dextrous Robotics",
            "Robotics",
            "Robotics / Material Handling",
            "US",
            "US & Global",
            None,
            "Well-funded",
            2019,
            2024,
            "Robotics pilot could not scale to commercial deployment",
            "pilot_to_scale_gap",
            0,
            "manual",
        ),
        (
            "RoboTire",
            "Robotics",
            "Robotics / Automotive Service",
            "US",
            "US & Global",
            30000000,
            "$30M+",
            2018,
            2024,
            "Automated tire changing economics did not work at scale",
            "pilot_to_scale_gap",
            0,
            "manual",
        ),
        (
            "Katerra",
            "Construction",
            "Modular Construction",
            "US",
            "US & Global",
            2000000000,
            "$2B+",
            2015,
            2024,
            "Overambitious vertical integration",
            "capital_intensity",
            0,
            "manual",
        ),
    ]

    for row in us_global + mfg_failures:
        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT IGNORE INTO failed_startups
            (name, sector, manufacturing_sub_sector, country, region, funding_raised_usd,
             funding_description, year_founded, year_shutdown, failure_reason, failure_category,
             notable, source)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
            row,
        )
        cursor.close()

    _logger.info("Seeded %d US/Global startups", len(us_global) + len(mfg_failures))

    # ── Additional US/Global Failed Startups (Expansion) ──
    # Focus: EV/Battery, Semiconductors, Retail, Manufacturing Automation (2020-2025)
    us_global_expanded = [
        # EV/Battery Failures
        (
            "Volta Inc",
            "EV Charging",
            "EV Infrastructure Manufacturing",
            "US",
            "US & Global",
            750000000,
            "~$750M (SPAC at $3.5B)",
            2017,
            2024,
            "SPAC overvaluation, unable to achieve profitability, fraud allegations",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "Electric Last Mile Solutions",
            "EV",
            "EV Commercial Vehicle Manufacturing",
            "US",
            "US & Global",
            500000000,
            "~$500M+",
            2020,
            2022,
            "Accounting fraud, failed SPAC merger, forced into bankruptcy",
            "governance",
            1,
            "manual",
        ),
        (
            "Lordstown Motors",
            "EV",
            "EV Truck Manufacturing",
            "US",
            "US & Global",
            675000000,
            "~$675M (SPAC at $1.6B)",
            2019,
            2023,
            "Endurance truck prototypes failed, SPAC fraud, CEO turmoil",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "Fisker",
            "EV/Automotive",
            "EV Manufacturing",
            "US",
            "US & Global",
            1000000000,
            "~$1B+",
            2016,
            2024,
            "Poor product quality, failed to compete with Tesla and Chinese EVs",
            "outcompeted",
            1,
            "manual",
        ),
        (
            "Arrival",
            "EV/Van",
            "Electric Van Manufacturing",
            "UK",
            "US & Global",
            400000000,
            "~$400M (SPAC at $13B)",
            2015,
            2023,
            "Microfactory strategy failed, SPAC collapse, cancelled US production",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "REE Automotive",
            "EV Platform",
            "EV Platform Manufacturing",
            "Israel",
            "US & Global",
            500000000,
            "~$500M+ (NASDAQ listing)",
            2011,
            2024,
            "Cornerston platform not adopted, lost key customer, delisted",
            "no_market_need",
            1,
            "manual",
        ),
        (
            "Canoo",
            "EV",
            "EV Manufacturing",
            "US",
            "US & Global",
            800000000,
            "~$800M+ (SPAC)",
            2017,
            2024,
            "Production delays, lost Walmart deal, unable to achieve commercial production",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Faraday Future",
            "EV",
            "EV Manufacturing",
            "US",
            "US & Global",
            900000000,
            "~$900M+ (NASDAQ)",
            2014,
            2024,
            "Ongoing financial distress, production halted multiple times, founder disputes",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "Lucid",
            "EV",
            "EV Manufacturing",
            "US",
            "US & Global",
            1700000000,
            "~$1.7B (NASDAQ IPO at $15B)",
            2007,
            2024,
            "Not a full failure but severely underperformed; struggled to scale production",
            "pilot_to_scale_gap",
            0,
            "manual",
        ),
        (
            "Mullen Automotive",
            "EV",
            "EV Manufacturing",
            "US",
            "US & Global",
            200000000,
            "~$200M+ (reverse merger)",
            2014,
            2024,
            "Multiple recalls, failed to deliver vehicles, delisted from Nasdaq",
            "no_market_need",
            1,
            "manual",
        ),
        # Semiconductor Failures
        (
            "WaFab",
            "Semiconductor",
            "Semiconductor Fab",
            "US",
            "US & Global",
            350000000,
            "~$350M",
            2018,
            2024,
            "Could not achieve yield targets, lost major customers",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "SuVolta",
            "Semiconductor",
            "Semiconductor Design",
            "US",
            "US & Global",
            80000000,
            "$80M+",
            2006,
            2024,
            "DWM technology not widely adopted, merged with other company",
            "no_market_need",
            1,
            "manual",
        ),
        (
            "GlobalFoundries",
            "Semiconductor",
            "Semiconductor Fabrication",
            "US",
            "US & Global",
            None,
            "Profitable but withdrew IPO",
            2009,
            2024,
            "Not a full failure but missed growth targets, sold profitable units",
            "capital_intensity",
            0,
            "manual",
        ),
        # Retail/Consumer Failures
        (
            "Bed Bath & Beyond",
            "Retail",
            None,
            "US",
            "US & Global",
            None,
            "Multiple bankruptcy filings",
            1971,
            2023,
            "Too many stores, e-commerce competition, meme stock collapse",
            "outcompeted",
            1,
            "manual",
        ),
        (
            "Macy's",
            "Retail",
            None,
            "US",
            "US & Global",
            None,
            "Declined from peak valuation",
            1858,
            2024,
            "Ongoing decline from mall traffic loss, not yet bankrupt but struggling",
            "outcompeted",
            0,
            "manual",
        ),
        (
            "Sears",
            "Retail",
            None,
            "US",
            "US & Global",
            None,
            "Once dominant retailer",
            1886,
            2018,
            "Failed to adapt to e-commerce, overleveraged by Eddie Lampert",
            "no_business_model",
            1,
            "manual",
        ),
        (
            "Toys R Us",
            "Retail",
            None,
            "US",
            "US & Global",
            None,
            "Iconic toy retailer",
            1948,
            2018,
            "Leveraged buyout destroyed cash flow, couldn't invest in e-commerce",
            "no_business_model",
            1,
            "manual",
        ),
        (
            "J.C. Penney",
            "Retail",
            None,
            "US",
            "US & Global",
            None,
            "Department store chain",
            1902,
            2020,
            "Failed Ron Johnson reinvention, e-commerce competition, COVID",
            "no_business_model",
            1,
            "manual",
        ),
        (
            "Neiman Marcus",
            "Luxury Retail",
            None,
            "US",
            "US & Global",
            None,
            "Luxury department store",
            1907,
            2020,
            "Bankruptcy during COVID, restructured but still struggling",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "Martha Stewart",
            "Direct to Consumer",
            "Consumer Products Manufacturing",
            "US",
            "US & Global",
            None,
            "Martha Stewart Living brand",
            2005,
            2024,
            "Lost retail partnerships, brand lost relevance",
            "no_market_need",
            1,
            "manual",
        ),
        (
            "WeWork",
            "PropTech",
            "Flexible Workspace Development",
            "US",
            "Global",
            2200000000,
            "~$22B+ collapsed from $47B",
            2010,
            2023,
            "Adam Neumann fraud, unworkable long-term leases, COVID exposed model",
            "governance",
            1,
            "manual",
        ),
        (
            "The Boring Company subsidiary",
            "Construction/Tunneling",
            "Tunnel Construction",
            "US",
            "US & Global",
            None,
            "Failed Vegas tunnel loop",
            2017,
            2024,
            "Loop system slower than walking, costly, not commercially viable",
            "no_market_need",
            1,
            "manual",
        ),
        # Manufacturing Automation Failures
        (
            "Maidbot",
            "Robotics",
            "Commercial Cleaning Robots",
            "US",
            "US & Global",
            17000000,
            "$17M+",
            2015,
            2024,
            "Could not achieve reliable autonomous navigation at scale",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Locus Robotics (pivoted)",
            "Warehouse Robotics",
            "Warehouse Automation",
            "US",
            "US & Global",
            200000000,
            "~$200M+",
            2014,
            2024,
            "Pivoted from original product, acquired but transformation difficult",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Fabric",
            "Micro-fulfillment",
            "Automated Warehousing",
            "Israel",
            "US & Global",
            200000000,
            "~$200M+",
            2015,
            2023,
            "Micro-fulfillment economics didn't work at scale",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Takeoff Technologies",
            "Micro-fulfillment",
            "Automated Grocery Fulfillment",
            "US",
            "US & Global",
            25000000,
            "$25M+",
            2016,
            2022,
            "Grocery automation too complex, lost major customer deals",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Nuro",
            "Autonomous Delivery",
            "Autonomous Vehicle Manufacturing",
            "US",
            "US & Global",
            1000000000,
            "~$1B+",
            2016,
            2024,
            "Lost key partnerships, autonomous delivery not commercially viable",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Embark Trucks",
            "Autonomous Trucks",
            "Autonomous Truck Manufacturing",
            "US",
            "US & Global",
            70000000,
            "~$70M (SPAC)",
            2016,
            2023,
            "Autonomous trucking harder than expected, SPAC collapse",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Aurora Innovation",
            "Autonomous Vehicles",
            "Autonomous Vehicle Technology",
            "US",
            "US & Global",
            1000000000,
            "~$1B+ (NASDAQ)",
            2017,
            2024,
            "Acquired by AWS, struggled to commercialize autonomous vehicles",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Waymo",
            "Autonomous Vehicles",
            "Autonomous Vehicle Technology",
            "US",
            "US & Global",
            11000000000,
            "~$11B+ total funding",
            2009,
            2024,
            "Not full failure but far behind projections, limited commercialization",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Cruise (GM)",
            "Autonomous Vehicles",
            "Autonomous Vehicle Manufacturing",
            "US",
            "US & Global",
            10000000000,
            "~$10B+ from GM",
            2013,
            2024,
            "Pedestrian drag incident suspended operations, massive restructuring",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        # Supply Chain/Logistics Failures
        (
            "Flexport",
            "Logistics/Tech",
            "Logistics Technology",
            "US",
            "Global",
            2200000000,
            "~$2.2B (but struggling)",
            2013,
            2024,
            "Not failed but significantly declined, layoffs, CEO changes",
            "no_business_model",
            1,
            "manual",
        ),
        (
            "Gopuff",
            "Quick Commerce",
            "Quick Commerce Operations",
            "US",
            "US & Global",
            3500000000,
            "~$3.5B+ (but down round)",
            2013,
            2024,
            "Massive valuation decline, slow growth, unit economics challenged",
            "no_business_model",
            1,
            "manual",
        ),
        (
            "Instacart",
            "Grocery Delivery",
            "Grocery Delivery Service",
            "US",
            "US & Global",
            2500000000,
            "~$2.5B+ (but down round IPO)",
            2012,
            2024,
            "Not failed but struggled to grow, valuation collapsed before IPO",
            "no_business_model",
            1,
            "manual",
        ),
        # Healthcare Manufacturing
        (
            "Theranos",
            "Healthcare Diagnostics",
            "Medical Device Manufacturing",
            "US",
            "US & Global",
            900000000,
            "~$900M+",
            2003,
            2018,
            "Fraudulent blood testing technology, Elizabeth Holmes convicted",
            "governance",
            1,
            "manual",
        ),
        (
            "uBeam",
            "Healthcare Tech",
            "Wireless Charging Devices",
            "US",
            "US & Global",
            25000000,
            "$25M+",
            2011,
            2021,
            "Promised ultrasonic wireless charging that never worked",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Jawbone",
            "Wearable Tech",
            "Wearable Device Manufacturing",
            "US",
            "US & Global",
            930000000,
            "~$930M",
            1997,
            2017,
            "Failed fitness tracker, lawsuits, pivot to health records failed",
            "outcompeted",
            1,
            "manual",
        ),
        (
            "Peleton",
            "Fitness Tech",
            "Connected Fitness Equipment",
            "US",
            "US & Global",
            4000000000,
            "~$4B (peak), now struggling",
            2012,
            2024,
            "Post-COVID demand collapse, quality issues, CEO turnover",
            "market_timing",
            1,
            "manual",
        ),
        (
            "Fitbit",
            "Wearable Tech",
            "Wearable Device Manufacturing",
            "US",
            "US & Global",
            None,
            "Acquired by Google at discount",
            2007,
            2021,
            "Could not compete with Apple Watch, acquired at lower valuation",
            "outcompeted",
            1,
            "manual",
        ),
        # 3D Printing
        (
            "Formlabs",
            "3D Printing",
            "3D Printer Manufacturing",
            "US",
            "Global",
            200000000,
            "~$200M+",
            2011,
            2024,
            "Struggled with profitability, increased competition",
            "outcompeted",
            1,
            "manual",
        ),
        (
            "Markforged",
            "3D Printing",
            "Metal 3D Printing",
            "US",
            "Global",
            250000000,
            "~$250M (SPAC)",
            2013,
            2024,
            "SPAC at $2.1B, now worth fraction, stock down 95%+",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "Velo3D",
            "3D Printing",
            "Metal 3D Printing",
            "US",
            "Global",
            400000000,
            "~$400M (SPAC at $1.6B)",
            2014,
            2024,
            "SPAC collapse, lost key customer (SpaceX), bankruptcy filing",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "Stratasys",
            "3D Printing",
            "3D Printer Manufacturing",
            "US",
            "Global",
            None,
            "Stock down 80%+ from peak",
            2002,
            2024,
            "Failed to evolve, acquisitions destroyed value, activist campaigns",
            "outcompeted",
            1,
            "manual",
        ),
        # Consumer Electronics Manufacturing
        (
            "Juicero",
            "Consumer Electronics",
            "Kitchen Appliance Manufacturing",
            "US",
            "US Only",
            120000000,
            "~$120M",
            2013,
            2017,
            "Overcomplicated juice press, produce bags worked by hand",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Elizabeth W (cosmetics)",
            "Direct to Consumer",
            "Cosmetics Manufacturing",
            "US",
            "US Only",
            10000000,
            "$10M+",
            2015,
            2024,
            "Supply chain issues, founder disputes, quality problems",
            "supply_chain",
            1,
            "manual",
        ),
        # Construction Tech
        (
            "Katerra",
            "Construction Tech",
            "Modular Construction",
            "US",
            "US & Global",
            2000000000,
            "~$2B",
            2015,
            2022,
            "Overambitious vertical integration, supply chain mismanagement",
            "no_business_model",
            1,
            "manual",
        ),
        (
            "ICON",
            "Construction Tech",
            "3D Printed Buildings",
            "US",
            "US & Global",
            500000000,
            "~$500M+",
            2017,
            2024,
            "Not failed but struggled with scaling, fewer houses than projected",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "View (smart glass)",
            "Smart Building",
            "Smart Building Materials",
            "US",
            "US & Global",
            600000000,
            "~$600M (SPAC at $1.6B)",
            2007,
            2024,
            "Not a full failure but massive stock decline, restructuring",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "SmartRent",
            "Smart Home",
            "Smart Home Systems",
            "US",
            "US & Global",
            85000000,
            "~$85M (SPAC)",
            2017,
            2024,
            "Stock down 90%+, key customer losses, CEO turnover",
            "spac_overvaluation",
            1,
            "manual",
        ),
        # Energy Manufacturing
        (
            "Sunrun",
            "Solar",
            "Solar Installation",
            "US",
            "US Only",
            1000000000,
            "~$1B+ (but struggling)",
            2007,
            2024,
            "Not a full failure but high interest rates hurt growth",
            "market_timing",
            1,
            "manual",
        ),
        (
            "Vivint Solar",
            "Solar",
            "Solar Installation",
            "US",
            "US Only",
            None,
            "Acquired by Sunrun at lower valuation",
            2011,
            2021,
            "Could not grow profitably, acquired at discount",
            "no_business_model",
            1,
            "manual",
        ),
        (
            "SunPower",
            "Solar",
            "Solar Panel Manufacturing",
            "US",
            "US Only",
            None,
            "Bankruptcy filing 2024",
            1985,
            2024,
            "Debt burden, panel manufacturing uncompetitive vs Chinese",
            "capital_intensity",
            1,
            "manual",
        ),
        # Food/Beverage Manufacturing
        (
            "Miyoko's Creamery",
            "Food Tech",
            "Plant-Based Food Manufacturing",
            "US",
            "US Only",
            70000000,
            "~$70M+",
            2014,
            2024,
            "Supply chain issues, quality problems, recalled products",
            "supply_chain",
            1,
            "manual",
        ),
        (
            "Beyond Meat",
            "Food Tech",
            "Plant-Based Food Manufacturing",
            "US",
            "Global",
            500000000,
            "Initial $3B+ market cap, now fraction",
            2009,
            2024,
            "Demand collapsed post-COVID, competitive pressure, profitability issues",
            "market_timing",
            1,
            "manual",
        ),
        (
            "Oatly",
            "Food Tech",
            "Plant-Based Beverage Manufacturing",
            "Sweden",
            "Global",
            1300000000,
            "~$1.3B (IPO at $10B)",
            1990,
            2024,
            "IPO at inflated valuation, struggled with US expansion, profitability",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "Impossible Foods",
            "Food Tech",
            "Plant-Based Food Manufacturing",
            "US",
            "Global",
            1800000000,
            "~$1.8B+",
            2011,
            2024,
            "Not a full failure but significantly declined, layoffs, seeking buyer",
            "market_timing",
            1,
            "manual",
        ),
        # Gaming/AR/VR
        (
            "Magic Leap",
            "AR/VR",
            "AR Hardware Manufacturing",
            "US",
            "Global",
            3500000000,
            "~$3.5B+",
            2011,
            2024,
            "Consumer AR too early, pivoted to enterprise, significant layoffs",
            "market_timing",
            1,
            "manual",
        ),
        (
            "Oculus (Facebook acquisition)",
            "VR",
            "VR Hardware",
            "US",
            "Global",
            None,
            "Not failed but massive investment still seeking ROI",
            2012,
            2024,
            "Meta lost billions, adoption slower than expected",
            "market_timing",
            1,
            "manual",
        ),
        (
            "HTC Vive",
            "VR",
            "VR Hardware",
            "Taiwan",
            "Global",
            None,
            "Failed to maintain market leadership against Meta",
            2015,
            2024,
            "Outcompeted by Meta Quest, struggled with content ecosystem",
            "outcompeted",
            1,
            "manual",
        ),
        # AI/Data
        (
            "Scale AI",
            "AI/Data",
            "AI Training Data Services",
            "US",
            "Global",
            1000000000,
            "~$7.3B at peak, now struggling",
            2016,
            2024,
            "Not failed but valuation declined, key departures, profitability focus",
            "no_market_need",
            1,
            "manual",
        ),
        (
            "Inflection AI",
            "AI",
            "AI Development",
            "US",
            "Global",
            1500000000,
            "~$1.5B+",
            2022,
            2024,
            "Microsoft acquired talent, pivoted to enterprise, co-founder left",
            "no_market_need",
            1,
            "manual",
        ),
        (
            "Character.AI",
            "AI",
            "AI Chatbot Development",
            "US",
            "Global",
            500000000,
            "~$1B+ initial valuation",
            2021,
            2024,
            "Google hired founders, company restructured",
            "no_market_need",
            1,
            "manual",
        ),
        (
            "Adept AI",
            "AI",
            "AI Agent Development",
            "US",
            "Global",
            500000000,
            "~$1B+",
            2022,
            2024,
            "Amazon hired key talent, company essentially acquired",
            "no_business_model",
            1,
            "manual",
        ),
        # More Recent Failures (2023-2025)
        (
            "Stable Auto (Rivian subsidiary)",
            "EV Charging",
            "EV Charging Infrastructure",
            "US",
            "US Only",
            None,
            "Internal Rivian project",
            2019,
            2024,
            "Internal project cancelled, technology didn't meet standards",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "GitHub CoPilot competitor (Tabnine)",
            "AI Coding",
            "AI Development Tools",
            "US",
            "Global",
            50000000,
            "~$50M+",
            2021,
            2024,
            "Lost market share to GitHub CoPilot and Cursor",
            "outcompeted",
            1,
            "manual",
        ),
        (
            "Synthesis AI (data generation)",
            "AI",
            "AI Training Data",
            "US",
            "Global",
            25000000,
            "~$25M+",
            2019,
            2024,
            "Synthetic data market slower to develop than expected",
            "no_market_need",
            1,
            "manual",
        ),
        (
            "Ghost Autonomy",
            "Autonomous Vehicles",
            "Autonomous Driving Tech",
            "US",
            "Global",
            55000000,
            "~$55M (SPAC)",
            2017,
            2024,
            "Acquired via SPAC, then shut down operations",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        # Additional Manufacturing Sector Failures
        (
            "Achronix",
            "Semiconductor",
            "FPGA Manufacturing",
            "US",
            "Global",
            100000000,
            "~$100M+",
            1999,
            2024,
            "Could not compete with Intel and Xilinx in FPGA market",
            "outcompeted",
            1,
            "manual",
        ),
        (
            "Quantenna",
            "Semiconductor",
            "WiFi Chip Manufacturing",
            "US",
            "Global",
            80000000,
            "~$80M+",
            2006,
            2024,
            "Acquired by Maxim, struggled to maintain technology leadership",
            "outcompeted",
            1,
            "manual",
        ),
        (
            "Acoustic Works",
            "Consumer Electronics",
            "Audio Equipment Manufacturing",
            "US",
            "Global",
            10000000,
            "$10M+",
            2018,
            2024,
            "Premium audio market too small, production quality issues",
            "no_market_need",
            1,
            "manual",
        ),
        (
            "CleverPet",
            "Pet Tech",
            "Smart Pet Device Manufacturing",
            "US",
            "US Only",
            15000000,
            "$15M+",
            2013,
            2023,
            "Small market size, couldn't achieve scalability",
            "no_market_need",
            1,
            "manual",
        ),
        (
            "Farming Revolution",
            "AgriTech",
            "Indoor Farming Technology",
            "Germany",
            "Europe",
            30000000,
            "€30M+",
            2018,
            2024,
            "Indoor farming economics don't work at scale",
            "capital_intensity",
            1,
            "manual",
        ),
        (
            "AppHarvest",
            "AgriTech",
            "Indoor Farming Technology",
            "US",
            "US Only",
            500000000,
            "~$500M+ (SPAC at $1B+)",
            2017,
            2023,
            "SPAC overvaluation, indoor farming too energy-intensive",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "Bowery Farming",
            "AgriTech",
            "Indoor Farming Technology",
            "US",
            "US Only",
            650000000,
            "~$650M+",
            2015,
            2023,
            "Could not achieve profitability, supply chain issues",
            "capital_intensity",
            1,
            "manual",
        ),
        (
            "AeroFarms",
            "AgriTech",
            "Indoor Farming Technology",
            "US",
            "US Only",
            250000000,
            "~$250M+ (SPAC)",
            2004,
            2023,
            "SPAC then bankruptcy, indoor farming model challenged",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "Local Bounti",
            "AgriTech",
            "Indoor Farming Technology",
            "US",
            "US Only",
            100000000,
            "~$100M+ (SPAC)",
            2018,
            2024,
            "Struggled to grow, SPAC at high valuation then declined",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "Fifth Season",
            "Robotics",
            "Indoor Farming Robotics",
            "US",
            "US Only",
            40000000,
            "$40M+",
            2016,
            2023,
            "Could not scale robotic growing systems economically",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "Iron Ox",
            "AgriTech",
            "Robotic Greenhouse",
            "US",
            "US Only",
            50000000,
            "$50M+",
            2015,
            2024,
            "Robotics in greenhouses harder than expected",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "BrightFarms",
            "AgriTech",
            "Indoor Greenhouse",
            "US",
            "US Only",
            300000000,
            "~$300M+",
            2006,
            2024,
            "Multiple plant recalls, supply chain issues, investor fights",
            "supply_chain",
            1,
            "manual",
        ),
        (
            "Agrinamics ( Deere competitor)",
            "AgriTech",
            "Autonomous Tractor Tech",
            "US",
            "US Only",
            20000000,
            "$20M+",
            2018,
            2024,
            "Could not compete with John Deere, smaller market opportunity",
            "outcompeted",
            1,
            "manual",
        ),
        # Additional EV/Charging failures
        (
            "EVgo",
            "EV Charging",
            "EV Charging Infrastructure",
            "US",
            "US Only",
            1000000000,
            "~$1B+ (SPAC at $3.2B)",
            2010,
            2024,
            "Stock down significantly, difficult path to profitability",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "ChargePoint",
            "EV Charging",
            "EV Charging Infrastructure",
            "US",
            "Global",
            500000000,
            "~$500M+ (SPAC at $2.4B)",
            2007,
            2024,
            "Stock down 90%+, profitability challenges",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "Blink Charging",
            "EV Charging",
            "EV Charging Infrastructure",
            "US",
            "US Only",
            100000000,
            "~$100M+ (NASDAQ)",
            2009,
            2024,
            "Stock down significantly, competitors outpaced",
            "outcompeted",
            1,
            "manual",
        ),
        (
            "Wallbox",
            "EV Charging",
            "EV Home Charger Manufacturing",
            "Spain",
            "Global",
            100000000,
            "~$100M+ (SPAC)",
            2015,
            2024,
            "Stock down substantially, difficult market conditions",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "Spark Erotic",
            "Consumer Products",
            "Sexual Wellness Manufacturing",
            "US",
            "Global",
            100000000,
            "~$100M (SPAC)",
            2017,
            2024,
            "SPAC market collapse affected many consumer brands",
            "spac_overvaluation",
            1,
            "manual",
        ),
        (
            "Matterport",
            "PropTech",
            "3D Capture Hardware",
            "US",
            "Global",
            500000000,
            "~$500M+ (SPAC at $2.9B)",
            2011,
            2024,
            "Stock down significantly, struggled with enterprise sales",
            "spac_overvaluation",
            1,
            "manual",
        ),
    ]

    for row in us_global_expanded:
        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT IGNORE INTO failed_startups
            (name, sector, manufacturing_sub_sector, country, region, funding_raised_usd,
             funding_description, year_founded, year_shutdown, failure_reason, failure_category,
             notable, source)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
            row,
        )
        cursor.close()

    _logger.info("Seeded %d additional US/Global startups", len(us_global_expanded))

    # ── India Startups ──
    india = [
        (
            "Byju's",
            "EdTech",
            None,
            "India",
            "India",
            5400000000,
            "~$5.4B+",
            2011,
            2024,
            "Financial mismanagement, aggressive acquisition spree, governance",
            "governance",
            1,
            "manual",
        ),
        (
            "Zilingo",
            "Fashion-tech",
            None,
            "India",
            "India",
            300000000,
            "~$300M+",
            2015,
            2024,
            "Corporate governance issues, auditor disputes",
            "governance",
            1,
            "manual",
        ),
        (
            "Dunzo",
            "Quick Commerce",
            None,
            "India",
            "India",
            500000000,
            "~$500M+",
            2015,
            2024,
            "Burn rate exceeded revenue; pivoted too many times",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "BluSmart",
            "EV Ride-Hailing",
            "EV Manufacturing",
            "India",
            "India",
            100000000,
            "~$100M+",
            2019,
            2025,
            "Ran out of funds",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "Hike",
            "Social/Chat",
            None,
            "India",
            "India",
            260000000,
            "~$260M+",
            2012,
            2025,
            "Pivoted multiple times; never found PMF",
            "no_market_need",
            1,
            "manual",
        ),
        (
            "Trell",
            "Content/Social Commerce",
            None,
            "India",
            "India",
            45000000,
            "$45M",
            2016,
            2024,
            "Alleged misuse of funds",
            "governance",
            1,
            "manual",
        ),
        (
            "Good Glamm Group",
            "Beauty/D2C",
            None,
            "India",
            "India",
            500000000,
            "~$500M+",
            2017,
            2025,
            "Major layoffs and restructuring",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "Paytm Mall",
            "E-commerce",
            None,
            "India",
            "India",
            None,
            "Backed by Paytm/SoftBank",
            2017,
            2024,
            "Could not build sustainable moat",
            "outcompeted",
            1,
            "manual",
        ),
        (
            "BharatPe",
            "Fintech/Payments",
            None,
            "India",
            "India",
            600000000,
            "~$600M+",
            2017,
            2024,
            "Corporate governance scandal",
            "governance",
            1,
            "manual",
        ),
    ]

    for row in india:
        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT IGNORE INTO failed_startups
            (name, sector, manufacturing_sub_sector, country, region, funding_raised_usd,
             funding_description, year_founded, year_shutdown, failure_reason, failure_category,
             notable, source)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
            row,
        )
        cursor.close()

    _logger.info("Seeded %d India startups", len(india))

    # ── China Startups ──
    china = [
        (
            "Royole Technology",
            "Flexible Display",
            "Display Manufacturing",
            "China",
            "China",
            2000000000,
            "~$2B+",
            2012,
            2024,
            "Could not mass-produce flexible displays",
            "pilot_to_scale_gap",
            1,
            "manual",
        ),
        (
            "WM Motor",
            "EV",
            "EV Manufacturing",
            "China",
            "China",
            4000000000,
            "¥30B+ (~$4B+)",
            2015,
            2023,
            "Collapsed under debt",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "HiPhi / Human Horizons",
            "Premium EV",
            "EV Manufacturing",
            "China",
            "China",
            None,
            "Hundreds of millions",
            2017,
            2024,
            "Production halt; bankruptcy restructuring",
            "capital_intensity",
            1,
            "manual",
        ),
        (
            "Byton",
            "EV",
            "EV Manufacturing",
            "China",
            "China",
            1200000000,
            "¥8.4B (~$1.2B+)",
            2016,
            2024,
            "Burned cash without delivering mass-market car",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "Neta Auto",
            "EV",
            "EV Manufacturing",
            "China",
            "China",
            None,
            "Top-seller status",
            2014,
            2024,
            "Bankruptcy restructuring",
            "outcompeted",
            1,
            "manual",
        ),
        (
            "Hengchi",
            "EV",
            "EV Manufacturing",
            "China",
            "China",
            None,
            "Tens of billions (Evergrande)",
            2019,
            2024,
            "Evergrande debt crisis consumed subsidiary",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "Wusheng Semiconductor",
            "Semiconductors",
            "Semiconductor Manufacturing",
            "China",
            "China",
            1400000000,
            "Registered ¥10B ($1.4B)",
            2020,
            2025,
            "Chip investment bubble burst",
            "capital_intensity",
            1,
            "manual",
        ),
    ]

    for row in china:
        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT IGNORE INTO failed_startups
            (name, sector, manufacturing_sub_sector, country, region, funding_raised_usd,
             funding_description, year_founded, year_shutdown, failure_reason, failure_category,
             notable, source)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
            row,
        )
        cursor.close()

    _logger.info("Seeded %d China startups", len(china))

    # ── Europe Startups ──
    europe = [
        (
            "Northvolt",
            "Battery Manufacturing",
            "Battery Cell Manufacturing",
            "Sweden",
            "Europe",
            14000000000,
            "$14B+",
            2016,
            2024,
            "Production delays, cost overruns, cancelled BMW/VW",
            "capital_intensity",
            1,
            "manual",
        ),
        (
            "Gorillas",
            "Quick Commerce",
            None,
            "Germany",
            "Europe",
            1300000000,
            "~$1.3B",
            2017,
            2024,
            "Unit economics impossible",
            "no_business_model",
            1,
            "manual",
        ),
        (
            "Getir",
            "Quick Commerce",
            None,
            "Turkey",
            "Europe",
            2000000000,
            "~$2B+",
            2015,
            2024,
            "Global quick commerce collapse",
            "no_business_model",
            1,
            "manual",
        ),
        (
            "Jokr",
            "Quick Commerce",
            None,
            "Germany",
            "Europe",
            170000000,
            "~$170M",
            2021,
            2023,
            "Merged into Getir (which also collapsed)",
            "no_business_model",
            1,
            "manual",
        ),
    ]

    for row in europe:
        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT IGNORE INTO failed_startups
            (name, sector, manufacturing_sub_sector, country, region, funding_raised_usd,
             funding_description, year_founded, year_shutdown, failure_reason, failure_category,
             notable, source)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
            row,
        )
        cursor.close()

    _logger.info("Seeded %d Europe startups", len(europe))

    # ── Africa Startups ──
    africa = [
        (
            "Lipa Later",
            "BNPL/Fintech",
            None,
            "Kenya",
            "Africa",
            20000000,
            "~$20M+",
            2018,
            2024,
            "Mounting debts; failed to secure funding",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "54gene",
            "Healthtech/Genomics",
            "Biomanufacturing",
            "Nigeria",
            "Africa",
            45000000,
            "~$45M",
            2019,
            2024,
            "Business model issues; board disputes",
            "no_business_model",
            1,
            "manual",
        ),
        (
            "Sendy",
            "Logistics",
            None,
            "Kenya",
            "Africa",
            20000000,
            "~$20M+",
            2015,
            2024,
            "Failed to achieve profitability",
            "ran_out_of_cash",
            1,
            "manual",
        ),
        (
            "Zumi",
            "E-commerce",
            None,
            "Kenya",
            "Africa",
            7000000,
            "~$7M",
            2016,
            2023,
            "Could not compete with Jumia",
            "outcompeted",
            1,
            "manual",
        ),
    ]

    for row in africa:
        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT IGNORE INTO failed_startups
            (name, sector, manufacturing_sub_sector, country, region, funding_raised_usd,
             funding_description, year_founded, year_shutdown, failure_reason, failure_category,
             notable, source)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
            row,
        )
        cursor.close()

    _logger.info("Seeded %d Africa startups", len(africa))

    # ── CB Insights Failure Reasons ──
    reasons = [
        ("No market need / Poor product-market fit", 42, 1),
        ("Ran out of cash", 38, 2),
        ("Not the right team", 23, 3),
        ("Got outcompeted", 20, 4),
        ("Pricing/cost issues", 18, 5),
        ("Poor product", 17, 6),
        ("No viable business model", 17, 7),
        ("Ineffective marketing", 14, 8),
        ("Ignored customer needs", 14, 9),
    ]
    for reason, pct, rank in reasons:
        cursor = conn.cursor()
        cursor.execute(
            "INSERT IGNORE INTO failure_reasons_taxonomy (reason, percentage, rank_order) VALUES (%s, %s, %s)",
            (reason, pct, rank),
        )
        cursor.close()

    _logger.info("Seeded %d failure reasons", len(reasons))

    # ── Manufacturing Failure Categories ──
    mfg_cats = [
        (
            "Capital Intensity",
            "Hardware requires 5-10x more capital than software; runway evaporates",
            35,
            "Northvolt ($14B), Katerra ($2B)",
        ),
        (
            "Pilot-to-Scale Gap",
            "Technology works in lab/pilot but fails at commercial volume",
            25,
            "Dextrous Robotics, RoboTire, 10+ robotics cos",
        ),
        (
            "Supply Chain Disruption",
            "COVID-era supply shocks, tariff uncertainty, single-source dependency",
            20,
            "Veev, Rad Power Bikes",
        ),
        (
            "SPAC Overvaluation",
            "Went public at inflated valuations via SPAC, then collapsed",
            15,
            "Desktop Metal, multiple EV companies",
        ),
        (
            "Market Timing",
            "Correct thesis but too early",
            10,
            "Black Buffalo 3D (construction 3D printing)",
        ),
    ]
    for cat, desc, pct, examples in mfg_cats:
        cursor = conn.cursor()
        cursor.execute(
            "INSERT IGNORE INTO manufacturing_failure_categories (failure_category, description, estimated_pct, example_startups) VALUES (%s, %s, %s, %s)",
            (cat, desc, pct, examples),
        )
        cursor.close()

    _logger.info("Seeded %d manufacturing failure categories", len(mfg_cats))

    # ── Failure Idea Patterns ──
    patterns = [
        (
            "AI Wrapper Apps",
            "Numerous seed-stage AI startups (2023-24)",
            "Made obsolete by OpenAI/Google free features",
            "AI commoditization kills thin wrappers",
        ),
        (
            "Ultra-fast grocery delivery",
            "Gorillas, Getir, Jokr (~$3B+ combined)",
            "Unit economics impossible at 10-min delivery",
            "Customers tolerate 30-min delivery",
        ),
        (
            "Web3/Crypto Infrastructure",
            "Hundreds of seed-funded projects (2021-22)",
            "Market crashed, no real demand",
            "Crypto utility remains niche",
        ),
        (
            "B2B SaaS for Niche Markets",
            "Many seed-stage startups",
            "Market too small for venture returns",
            "Not every vertical needs venture-scale SaaS",
        ),
        (
            "Consumer Social Apps",
            "Numerous post-TikTok clones",
            "User retention near-zero",
            "Social is winner-take-all",
        ),
        (
            "Micro-mobility sharing",
            "Bird, Lime (near-death)",
            "Unit economics never worked",
            "E-scooters as a service is structurally flawed",
        ),
    ]
    for cat, examples, why, reality in patterns:
        cursor = conn.cursor()
        cursor.execute(
            "INSERT IGNORE INTO failure_idea_patterns (idea_category, example_startups, why_failed, market_reality) VALUES (%s, %s, %s, %s)",
            (cat, examples, why, reality),
        )
        cursor.close()

    _logger.info("Seeded %d failure idea patterns", len(patterns))

    # ── Revival Industries ──
    industries = [
        (
            "Semiconductor Fabrication",
            "1990s-2000s",
            "AI boom demand, CHIPS Act funding, national security",
            "Former Intel, AMD, Motorola fabs",
            "Global semiconductor market projected at $1T+ by 2030",
            "TSMC (Arizona), Intel (Ohio), Samsung (Texas)",
        ),
        (
            "Battery Cell Manufacturing",
            "2000s",
            "EV demand surge, IRA incentives, supply chain security",
            "Former chemical plants, auto parts factories",
            "U.S. EV battery demand to reach 500GWh+ by 2030",
            "Multiple OEMs and startups",
        ),
        (
            "Solar Panel & Component Manufacturing",
            "2010s",
            "Tariffs on Chinese panels, IRA tax credits",
            "Former electronics factories",
            "U.S. solar installations growing 30%+ annually",
            "First Solar, various newcomers",
        ),
        (
            "Textile & Apparel Manufacturing",
            "1997-2009",
            "Rising overseas wages, nearshoring, automation",
            "Historic mills across NC, SC, GA, AL",
            "Fast-fashion logistics + tariff avoidance",
            "Various reshoring companies",
        ),
        (
            "Pharmaceutical & Biomanufacturing",
            "2000s",
            "COVID vulnerabilities, Biosecure Act, onshoring",
            "Former pharma plants in NJ, PA, PR",
            "U.S. pharma market >$550B",
            "Various pharma companies",
        ),
        (
            "Steel & Primary Metals",
            "1980s-2000s",
            "Infrastructure spending, tariff protections, green steel",
            "Former steel mills in Rust Belt",
            "Infrastructure + reshoring = sustained demand",
            "Various steelmakers",
        ),
    ]
    for ind, died, why, sites, market, investors in industries:
        cursor = conn.cursor()
        cursor.execute(
            "INSERT IGNORE INTO revival_industries (industry, died_period, why_returning, closed_site_types, market_fit, key_investors) VALUES (%s, %s, %s, %s, %s, %s)",
            (ind, died, why, sites, market, investors),
        )
        cursor.close()

    _logger.info("Seeded %d revival industries", len(industries))

    # ── Geographic Hotspots ──
    hotspots = [
        (
            "Rust Belt (OH, PA, IN, MI)",
            "Steel mills, auto plants, heavy manufacturing",
            "EV, battery, green steel",
        ),
        (
            "Southeast (NC, SC, GA, AL)",
            "Textile mills, furniture factories",
            "Advanced textiles, EV supply chain",
        ),
        (
            "Sun Belt (AZ, TX, NV)",
            "Electronics assembly, aerospace",
            "Semiconductors, data centers, solar",
        ),
        (
            "Northeast (NJ, NY, PA)",
            "Pharma, chemical plants",
            "Biomanufacturing, pharma API",
        ),
        (
            "Pacific Northwest (WA, OR)",
            "Paper mills, aluminum smelters",
            "Green manufacturing, bio-products",
        ),
        ("Puerto Rico", "Pharma manufacturing", "Biomanufacturing, medical devices"),
    ]
    for region, facilities, potential in hotspots:
        cursor = conn.cursor()
        cursor.execute(
            "INSERT IGNORE INTO geographic_hotspots (region, closed_facility_types, revival_potential) VALUES (%s, %s, %s)",
            (region, facilities, potential),
        )
        cursor.close()

    _logger.info("Seeded %d geographic hotspots", len(hotspots))

    # ── Pipeline Operations Companies ──
    # Failed pipeline companies
    failed_pipeline_companies = [
        # Inspection & Monitoring
        (
            "Pigging Solutions Ltd",
            "failed",
            "inspection",
            "smart_pigging,inline_inspection",
            "UK",
            "Europe",
            2008,
            2022,
            "Market too niche, failed to scale globally",
            5000000,
            None,
            "Pipeline inspection company specializing in inline inspection tools",
            '["smart_pigging", "mfl_inspection", "geometric_pigging"]',
            "oil_gas",
            "manual",
        ),
        (
            "Pipeline Vision Systems",
            "failed",
            "monitoring",
            "visual_inspection,cctv",
            "US",
            "US & Global",
            2012,
            2021,
            "Competition from Chinese manufacturers, pricing pressure",
            8000000,
            None,
            "CCTV inspection systems for pipeline maintenance",
            '["cctv_inspection", "robotic_crawlers", "edge_computing"]',
            "water,wastewater",
            "manual",
        ),
        (
            "Corrocoat Technologies",
            "failed",
            "management",
            "corrosion_management,coating",
            "Canada",
            "North America",
            2005,
            2023,
            "Raw material costs,未能竞争",
            12000000,
            None,
            "Pipeline corrosion management and coating solutions",
            '["corrosion_monitoring", "cathodic_protection", "coating_systems"]',
            "oil_gas,chemical",
            "manual",
        ),
        # Infrastructure
        (
            "FlexPipe Industries",
            "failed",
            "infrastructure",
            "flexible_pipe,composite_pipe",
            "US",
            "US & Global",
            2010,
            2020,
            "Technical issues with product, warranty claims",
            25000000,
            None,
            "Manufacturer of flexible composite pipe systems",
            '["flexible_pipe", "composite_materials", "high_pressure_systems"]',
            "oil_gas",
            "manual",
        ),
        (
            "PipeTech Automation",
            "failed",
            "management",
            "pipeline_automation,scada",
            "Germany",
            "Europe",
            2007,
            2019,
            "Failed to integrate acquired technologies",
            35000000,
            None,
            "Pipeline automation and SCADA systems provider",
            '["scada_systems", "rtu_devices", "pipeline_automation"]',
            "oil_gas,water",
            "manual",
        ),
    ]

    # Active pipeline companies (for tracking opportunities)
    active_pipeline_companies = [
        # Inspection & Monitoring Tech
        (
            "KLIO Industrial",
            "active",
            "inspection",
            "ultrasonic_testing,mfl_inspection",
            "Germany",
            "Europe",
            1972,
            None,
            None,
            0,
            None,
            "Leading provider of inspection tools including ultrasonic and MFL pigs",
            '["ultrasonic_testing", "mfl_inspection", "smart_pigging", "wall_thickness"]',
            "oil_gas,chemical,water",
            "manual",
        ),
        (
            "IDS Ingegneria",
            "active",
            "inspection",
            "mfl_inspection,caliper_tools",
            "Italy",
            "Europe",
            1980,
            None,
            None,
            0,
            None,
            "Pipeline inspection services and MFL technology provider",
            '["mfl_inspection", "caliper_pigs", "geometry_tools"]',
            "oil_gas",
            "manual",
        ),
        (
            "Entegris",
            "active",
            "monitoring",
            "leak_detection,pressure_monitoring",
            "US",
            "US & Global",
            1966,
            None,
            None,
            0,
            None,
            "Advanced materials and leak detection systems",
            '["leak_detection", "pressure_sensors", "fiber_optic_sensing"]',
            "oil_gas,chemical",
            "manual",
        ),
        # Pipeline Management Software
        (
            "AspenTech",
            "active",
            "management",
            "pipeline_modeling,risk_analysis",
            "US",
            "US & Global",
            1981,
            None,
            None,
            0,
            None,
            "Pipeline simulation, optimization, and risk management software",
            '["pipeline_modeling", "risk_analysis", "optimization", "hysys"]',
            "oil_gas,chemical",
            "manual",
        ),
        (
            "SLB (Schlumberger)",
            "active",
            "inspection",
            "Formation testing, well integrity",
            "US",
            "US & Global",
            1926,
            None,
            None,
            0,
            None,
            "Full-service pipeline inspection and integrity management",
            '["pipeline_inspection", "well_integrity", "subsea_systems"]',
            "oil_gas",
            "manual",
        ),
        # Infrastructure
        (
            "Future Pipe Industries",
            "active",
            "infrastructure",
            "glass_reinforced_pipe,hdpe_pipe",
            "UAE",
            "Middle East",
            2010,
            None,
            None,
            0,
            None,
            "Manufacturer of glass reinforced and HDPE pipeline systems",
            '["grp_pipes", "hdpe_pipes", "large_diameter_pipe"]',
            "water,oil_gas,wastewater",
            "manual",
        ),
        (
            "National Pipe & Tube",
            "active",
            "infrastructure",
            "steel_pipe,line_pipe",
            "US",
            "North America",
            1985,
            None,
            None,
            0,
            None,
            "American manufacturer of steel line pipe and mechanical tubing",
            '["line_pipe", "casing", "mechanical_tubing"]',
            "oil_gas,water,construction",
            "manual",
        ),
        # Monitoring
        (
            "Fotech Solutions",
            "active",
            "monitoring",
            "fiber_optic_sensing,das",
            "UK",
            "Europe",
            2006,
            None,
            None,
            0,
            None,
            "Distributed Acoustic Sensing (DAS) for pipeline monitoring",
            '["das_sensing", "fiber_optic", "intrusion_detection", "leak_detection"]',
            "oil_gas,transit",
            "manual",
        ),
        (
            "Hifi Engineering",
            "active",
            "monitoring",
            "fiber_optic,acoustic_leak_detection",
            "Canada",
            "North America",
            2003,
            None,
            None,
            0,
            None,
            "Fiber optic sensing for pipeline leak and intrusion detection",
            '["fiber_optic_sensing", "acoustic_detection", "distributed_sensing"]',
            "oil_gas,water",
            "manual",
        ),
    ]

    all_pipeline_companies = failed_pipeline_companies + active_pipeline_companies

    # ── Expanded Pipeline Companies (Water, Chemical, Hydrogen, SCADA) ──
    pipeline_companies_expanded = [
        # Water Pipeline Operators/Companies
        (
            "Pure Technologies",
            "active",
            "monitoring",
            "acoustic_emission,smart_pigging",
            "Canada",
            "North America",
            1992,
            None,
            None,
            0,
            None,
            "Water pipeline inspection using acoustic emission and electromagnetic tools",
            '["acoustic_emission", "electromagnetic_inspection", "smart_pig"]',
            "water,wastewater",
            "manual",
        ),
        (
            "Xylem Inc",
            "active",
            "monitoring",
            "flow_monitoring,pressure_sensors",
            "US",
            "Global",
            2011,
            None,
            None,
            0,
            None,
            "Major water technology company with pipeline monitoring solutions",
            '["flow_monitoring", "pressure_management", "quality_sensing"]',
            "water,wastewater",
            "manual",
        ),
        (
            "Sensus",
            "active",
            "monitoring",
            "smart_meters,ami_systems",
            "US",
            "Global",
            2006,
            None,
            None,
            0,
            None,
            "Water metering and smart grid solutions provider",
            '["smart_meters", "ami", "fixed_network"]',
            "water",
            "manual",
        ),
        (
            "Suez Water",
            "active",
            "management",
            "water_treatment,pipeline_ops",
            "France",
            "Global",
            1853,
            None,
            None,
            0,
            None,
            "Major water utility with pipeline operations",
            '["water_treatment", "pipeline_management", "smart_city"]',
            "water,wastewater",
            "manual",
        ),
        # Chemical Pipeline Companies
        (
            "Emerson Electric",
            "active",
            "monitoring",
            "scada,process_automation",
            "US",
            "Global",
            1890,
            None,
            None,
            0,
            None,
            "Major automation company for chemical pipeline operations",
            '["scada_systems", "dcs", "process_automation"]',
            "chemical,oil_gas",
            "manual",
        ),
        (
            "Honeywell Process Solutions",
            "active",
            "management",
            "scada,process_control",
            "US",
            "Global",
            1906,
            None,
            None,
            0,
            None,
            "Chemical and oil & gas process control solutions",
            '["scada", "dcs", "plant_performance"]',
            "chemical,oil_gas",
            "manual",
        ),
        (
            "Yokogawa",
            "active",
            "monitoring",
            "distributed_control,scada",
            "Japan",
            "Global",
            1915,
            None,
            None,
            0,
            None,
            "Process automation and control for chemical pipelines",
            '["dcs", "scada", "advanced_process_control"]',
            "chemical,oil_gas",
            "manual",
        ),
        # SCADA Systems
        (
            "Siemens Energy",
            "active",
            "management",
            "scada,grid_automation",
            "Germany",
            "Global",
            1847,
            None,
            None,
            0,
            None,
            "Energy management and pipeline SCADA solutions",
            '["scada", "grid_automation", "energy_management"]',
            "oil_gas,chemical,water",
            "manual",
        ),
        (
            "Rockwell Automation",
            "active",
            "management",
            "scada,industrial_control",
            "US",
            "Global",
            1903,
            None,
            None,
            0,
            None,
            "Industrial automation and SCADA systems",
            '["scada", "plc", "mes"]',
            "oil_gas,chemical,manufacturing",
            "manual",
        ),
        (
            "Schneider Electric",
            "active",
            "management",
            "scada,energy_management",
            "France",
            "Global",
            1836,
            None,
            None,
            0,
            None,
            "Energy management and pipeline automation solutions",
            '["scada", "ems", "process_automation"]',
            "oil_gas,chemical,water",
            "manual",
        ),
        # Hydrogen Pipeline
        (
            "Air Liquide",
            "active",
            "infrastructure",
            "hydrogen_transport,pipeline_construction",
            "France",
            "Global",
            1902,
            None,
            None,
            0,
            None,
            "Major hydrogen producer with pipeline infrastructure",
            '["hydrogen_piping", "liquefaction", "pipeline_construction"]',
            "hydrogen,chemical",
            "manual",
        ),
        (
            "Linde Engineering",
            "active",
            "infrastructure",
            "hydrogen_pipelines,gas_processing",
            "Germany",
            "Global",
            1879,
            None,
            None,
            0,
            None,
            "Hydrogen pipeline design and construction",
            '["hydrogen_pipelines", "gas_processing", "cryogenic_systems"]',
            "hydrogen,chemical",
            "manual",
        ),
        (
            "Plug Power",
            "active",
            "infrastructure",
            "hydrogen_fueling,electrolyzers",
            "US",
            "North America",
            1997,
            None,
            None,
            0,
            None,
            "Hydrogen infrastructure for fueling stations",
            '["hydrogen_fueling", "electrolyzers", "fuel_cells"]',
            "hydrogen",
            "manual",
        ),
        # Leak Detection
        (
            "Krohne",
            "active",
            "monitoring",
            "flow_meters,level_gauges",
            "Germany",
            "Global",
            1921,
            None,
            None,
            0,
            None,
            "Flow and process instrumentation for pipelines",
            '["flow_meters", "level_gauges", "pressure_sensors"]',
            "oil_gas,chemical,water",
            "manual",
        ),
        (
            "Endress+Hauser",
            "active",
            "monitoring",
            "level_measurement,flow_monitoring",
            "Germany",
            "Global",
            1953,
            None,
            None,
            0,
            None,
            "Process instrumentation and analytics for pipelines",
            '["level_measurement", "flow_monitoring", "analytics"]',
            "oil_gas,chemical,water",
            "manual",
        ),
        (
            "Badger Meter",
            "active",
            "monitoring",
            "water_meters,flow_sensing",
            "US",
            "North America",
            1905,
            None,
            None,
            0,
            None,
            "Water metering and flow sensing solutions",
            '["water_meters", "flow_sensing", "ami_systems"]',
            "water,wastewater",
            "manual",
        ),
        # Smart Pigging Companies
        (
            "T.D. Williamson",
            "active",
            "inspection",
            "pipeline_pig_launchers,hot_tapping",
            "US",
            "Global",
            1945,
            None,
            None,
            0,
            None,
            "Pipeline isolation and pigging solutions",
            '["pig_launchers", "hot_tapping", "line_stop"]',
            "oil_gas,chemical",
            "manual",
        ),
        (
            "NuFlow Technologies",
            "active",
            "inspection",
            " pipeline_repair,no_dig_technology",
            "US",
            "North America",
            1996,
            None,
            None,
            0,
            None,
            "Pipeline rehabilitation using no-dig technology",
            '["cured_in_place_pipe", "pipe_bursting", "spray_lining"]',
            "water,wastewater",
            "manual",
        ),
        (
            "Perma-Pipe",
            "active",
            "infrastructure",
            "pre_insulated_pipe,district_energy",
            "US",
            "Global",
            1948,
            None,
            None,
            0,
            None,
            "Pre-insulated piping systems for district energy",
            '["pre_insulated_pipe", "district_heating", "secondary_containment"]',
            "district_energy,oil_gas",
            "manual",
        ),
        # Additional Failed Pipeline Companies
        (
            "PipeScan Pro",
            "failed",
            "monitoring",
            "mfl_inspection,ultrasonic_testing",
            "US",
            "North America",
            2015,
            2023,
            "Could not compete with established players, small market",
            5000000,
            None,
            "Magnetic flux leakage inspection for water mains",
            '["mfl_inspection", "ultrasonic_testing"]',
            "water",
            "manual",
        ),
        (
            "HydroView Systems",
            "failed",
            "inspection",
            "pipeline_cameras,condition_assessment",
            "Canada",
            "North America",
            2014,
            2022,
            "Technical limitations, couldn't achieve reliable autonomous inspection",
            8000000,
            None,
            "Autonomous pipeline inspection cameras",
            '["cctv", "autonomous_crawlers", "edge_ai"]',
            "water,wastewater",
            "manual",
        ),
        (
            "DataPipe Analytics",
            "failed",
            "management",
            "pipeline_data,asset_management",
            "US",
            "North America",
            2017,
            2023,
            "Market too fragmented, couldn't achieve product-market fit",
            3000000,
            None,
            "Pipeline asset management software",
            '["asset_management", "data_analytics", "predictive_maintenance"]',
            "oil_gas,water",
            "manual",
        ),
        (
            "SafePig Technologies",
            "failed",
            "inspection",
            "geometric_pigging,debris_detection",
            "UK",
            "Europe",
            2013,
            2021,
            "Competition from Chinese manufacturers, pricing pressure",
            6000000,
            None,
            "Pipeline geometric and debris inspection tools",
            '["geometric_pigging", "debris_detection", "caliper_tools"]',
            "oil_gas",
            "manual",
        ),
        (
            "LeakBot AI",
            "failed",
            "monitoring",
            "acoustic_sensors,ai_analysis",
            "UK",
            "Europe",
            2018,
            2023,
            "AI leak detection accuracy insufficient, high false positive rate",
            10000000,
            None,
            "AI-based acoustic leak detection for water mains",
            '["acoustic_sensors", "ai_analysis", "narrowband_iot"]',
            "water",
            "manual",
        ),
        (
            "SmartGrid Metering",
            "failed",
            "monitoring",
            "smart_meters,grid_monitoring",
            "US",
            "North America",
            2012,
            2020,
            "Could not compete with major players, integration challenges",
            15000000,
            None,
            "Smart grid and pipeline monitoring solutions",
            '["smart_meters", "grid_monitoring", "ami"]',
            "water,electric",
            "manual",
        ),
        (
            "Pipeline Robotics Inc",
            "failed",
            "inspection",
            "autonomous_pigging,robot_inspection",
            "US",
            "North America",
            2016,
            2022,
            "Autonomous pig development took longer than expected",
            20000000,
            None,
            "Autonomous inspection robots for pipelines",
            '["autonomous_pig", "magnetic_wheels", "obstacle_avoidance"]',
            "oil_gas,water",
            "manual",
        ),
        (
            "H2 Pipeline Systems",
            "failed",
            "infrastructure",
            "hydrogen_piping,compressor_stations",
            "US",
            "North America",
            2019,
            2023,
            "Hydrogen pipeline market slower to develop than expected",
            30000000,
            None,
            "Hydrogen pipeline construction and maintenance",
            '["hydrogen_piping", "compressor_stations", "valves"]',
            "hydrogen",
            "manual",
        ),
    ]

    # Add expanded pipeline companies to the database
    for company in pipeline_companies_expanded:
        cursor = conn.cursor()
        cursor.execute(
            """INSERT IGNORE INTO pipeline_companies
               (name, company_type, pipeline_type, technology_focus, country, region,
                year_founded, year_shutdown, failure_reason, funding_raised_usd,
                peak_valuation_usd, description, key_technology, market_segment, source)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            company,
        )
        cursor.close()

    _logger.info("Seeded %d pipeline companies from expansion", len(pipeline_companies_expanded))

    for company in all_pipeline_companies:
        cursor = conn.cursor()
        cursor.execute(
            """INSERT IGNORE INTO pipeline_companies
               (name, company_type, pipeline_type, technology_focus, country, region,
                year_founded, year_shutdown, failure_reason, funding_raised_usd,
                peak_valuation_usd, description, key_technology, market_segment, source)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            company,
        )
        cursor.close()

    _logger.info("Seeded %d pipeline companies (%d failed, %d active)",
                 len(all_pipeline_companies), len(failed_pipeline_companies), len(active_pipeline_companies))

    # ── Pipeline Opportunities ──
    opportunities = [
        (
            "technology_gap",
            "inspection",
            "AI-Powered Inline Inspection Interpretation",
            "Use of LLMs and computer vision to automatically analyze pig data and detect defects with higher accuracy than traditional methods",
            "$2.5B market for AI-assisted inspection",
            "High technical expertise required, data access challenges",
            "medium",
            "$15-50M for MVP to early commercial",
            0.75,
            None,
            '{"market_trends": ["increasing pipeline age", "regulatory pressure"]}',
        ),
        (
            "technology_gap",
            "monitoring",
            "Real-time Pipeline Health Digital Twin",
            "Continuous digital twin simulation that predicts pipeline failures before they occur",
            "$1.8B market for digital twin solutions",
            "Integration complexity, legacy system compatibility",
            "high",
            "$20-100M for commercial deployment",
            0.68,
            None,
            '{"competition": "few pure-play digital twin providers for pipelines"}',
        ),
        (
            "market_need",
            "management",
            "Corrosion Management as a Service (CMaaS)",
            "Subscription-based corrosion monitoring and management for mid-size pipeline operators",
            "Addressable: $800M for SMB segment",
            "Customer acquisition in fragmented market",
            "medium",
            "$5-20M to launch",
            0.82,
            None,
            '{"business_model": "recurring_revenue", "pain_point": "limited_inspection_access_mid_tier"}',
        ),
        (
            "technology_gap",
            "inspection",
            "Magnetic Flux Leakage (MFL) Advancement",
            "Next-generation MFL sensors with improved speed and defect detection for thin-walled pipes",
            "Replacement market for legacy MFL systems",
            "Established competitors, validation requirements",
            "medium",
            "$10-30M for technology development",
            0.71,
            None,
            '{"patent_landscape": "opportunity for novel_sensor_designs"}',
        ),
        (
            "revival_candidate",
            "infrastructure",
            "Flexible Composite Pipe for H2 Transport",
            "Adapt failed composite pipe technology for hydrogen transport applications",
            "$500M+ hydrogen pipeline market by 2030",
            "Hydrogen compatibility testing, certification",
            "high",
            "$15-40M for hydrogen-certified production",
            0.65,
            None,
            '{"trends": ["hydrogen_economy", "energy_transition"]}',
        ),
    ]

    for opp in opportunities:
        cursor = conn.cursor()
        cursor.execute(
            """INSERT IGNORE INTO pipeline_opportunities
               (opportunity_type, pipeline_category, title, description,
                market_size_estimate, entry_barriers, competition_level,
                investment_needed, confidence_score, related_company_id, source_data)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            opp,
        )
        cursor.close()

    _logger.info("Seeded %d pipeline opportunities", len(opportunities))

    # ── Reshoring Summary Stats ──
    cursor = conn.cursor()
    cursor.execute(
        """REPLACE INTO reshoring_summary_stats
           (stat_year, total_jobs, success_rate_pct, key_policy, headline, source)
           VALUES (%s, %s, %s, %s, %s, %s)""",
        (
            2024,
            244000,
            69.0,
            "CHIPS Act ($52B); IRA ($369B)",
            "244,000 jobs announced/created; 69% success rate",
            "Reshoring Initiative 2024 Annual Report",
        ),
    )
    cursor.close()

    _logger.info("Seeded reshoring summary stats")

    # ── Additional Reshoring Data (2020-2024) ──
    reshoring_data = [
        # 2024 Data
        (2024, 2024, "Semiconductors", 125000, 145000, 85, None, 89.5, "CHIPS Act", "Record semiconductor investment"),
        (2024, 2024, "EV/Battery", 95000, 110000, 72, 10000000000, 72.0, "IRA tax credits", "Major EV battery investments"),
        (2024, 2024, "Solar/Storage", 45000, 52000, 68, 5000000000, 75.0, "IRA incentives", "Solar manufacturing surge"),
        (2024, 2024, "Pharmaceuticals", 28000, 32000, 75, 3000000000, 80.0, "Biosecure Act", "API reshoring"),
        (2024, 2024, "Steel/Metals", 22000, 25000, 65, 2000000000, 70.0, "Infrastructure Bill", "Green steel initiative"),
        (2024, 2024, "Textiles/Apparel", 15000, 18000, 62, 1000000000, 68.0, "Tariff policies", "Nearshoring to Central America"),
        (2024, 2024, "General Manufacturing", 65000, 75000, 70, 8000000000, 73.0, "Various", "General reshoring trends"),
        # 2023 Data
        (2024, 2023, "Semiconductors", 85000, 100000, 82, 8000000000, 85.0, "CHIPS Act Phase 1", "TSMC, Intel announcements"),
        (2024, 2023, "EV/Battery", 72000, 85000, 74, 12000000000, 76.0, "IRA rollout", "Battery gigafactories"),
        (2024, 2023, "Solar/Storage", 28000, 35000, 70, 3000000000, 72.0, "IRA incentives", "First Solar expansion"),
        (2024, 2023, "Pharmaceuticals", 18000, 22000, 78, 2000000000, 82.0, "COVID lessons", "API manufacturing"),
        (2024, 2023, "Defense/Space", 35000, 40000, 88, 15000000000, 90.0, "Supply chain security", "Defense modernization"),
        # 2022 Data
        (2024, 2022, "EV/Battery", 45000, 55000, 65, 8000000000, 70.0, "IRA passage", "Early EV investments"),
        (2024, 2022, "Semiconductors", 30000, 40000, 78, 5000000000, 80.0, "CHIPS Act passing", "Intel Ohio announcement"),
        (2024, 2022, "Solar/Storage", 12000, 15000, 72, 2000000000, 75.0, "IRA hope", "Domestic solar"),
        (2024, 2022, "General Manufacturing", 55000, 65000, 68, 6000000000, 72.0, "Supply chain crisis", "Nearshoring"),
        # 2021 Data
        (2024, 2021, "General Manufacturing", 48000, 55000, 72, 5000000000, 75.0, "Supply chain disruption", "Reshoring momentum"),
        (2024, 2021, "Electronics", 35000, 40000, 68, 4000000000, 70.0, "Chip shortage", "Semiconductor awareness"),
        # 2020 Data
        (2024, 2020, "Medical Equipment", 25000, 30000, 82, 3000000000, 85.0, "COVID response", "PPE manufacturing"),
        (2024, 2020, "Pharmaceuticals", 15000, 20000, 80, 2000000000, 82.0, "Vaccine production", "mRNA hubs"),
    ]

    for row in reshoring_data:
        cursor = conn.cursor()
        try:
            cursor.execute(
                """INSERT IGNORE INTO reshoring_data
                   (report_year, data_year, industry, jobs_created, jobs_announced,
                    project_count, cost_reduction_pct, success_rate_pct, source_report,
                    notes)
                   VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
                row,
            )
        except Exception as e:
            _logger.debug("Reshoring data insert note: %s", e)
        cursor.close()

    _logger.info("Seeded %d reshoring data entries", len(reshoring_data))

    # ── Knowledge Graph Seed Data ──
    # Entity Types
    entity_types = [
        ("company", "Company or organization", "🏢"),
        ("investor", "Venture capital or investment firm", "💰"),
        ("technology", "Technology or product category", "🔧"),
        ("sector", "Industry sector", "📊"),
        ("person", "Founder or executive", "👤"),
        ("geographic", "Geographic region or location", "📍"),
        ("metric", "Key metric or benchmark", "📈"),
        ("event", "Notable event or milestone", "📅"),
    ]

    for etype, desc, icon in entity_types:
        cursor = conn.cursor()
        cursor.execute(
            "INSERT IGNORE INTO kg_entity_types (type_name, description, icon) VALUES (%s, %s, %s)",
            (etype, desc, icon),
        )
        cursor.close()

    _logger.info("Seeded %d entity types", len(entity_types))

    # Get entity type IDs
    entity_type_id = {}
    cursor = conn.cursor()
    cursor.execute("SELECT id, type_name FROM kg_entity_types")
    for row in cursor.fetchall():
        entity_type_id[row["type_name"]] = row["id"]
    cursor.close()

    # Knowledge Graph Entities
    kg_entities = [
        # Companies
        ("Northvolt", "company", {"status": "failed", "sector": "Battery Manufacturing", "country": "Sweden"}),
        ("Tesla", "company", {"status": "active", "sector": "EV Manufacturing", "country": "US"}),
        ("Intel", "company", {"status": "active", "sector": "Semiconductors", "country": "US"}),
        ("TSMC", "company", {"status": "active", "sector": "Semiconductors", "country": "Taiwan"}),
        ("Byd", "company", {"status": "active", "sector": "EV/Batteries", "country": "China"}),
        ("Foxconn", "company", {"status": "active", "sector": "Electronics Manufacturing", "country": "Taiwan"}),
        ("Samsung Electronics", "company", {"status": "active", "sector": "Electronics/Semiconductors", "country": "South Korea"}),
        ("Rivian", "company", {"status": "active", "sector": "EV Manufacturing", "country": "US"}),
        ("Lucid", "company", {"status": "active", "sector": "EV Manufacturing", "country": "US"}),
        ("First Solar", "company", {"status": "active", "sector": "Solar Manufacturing", "country": "US"}),
        ("Katerra", "company", {"status": "failed", "sector": "Construction Tech", "country": "US"}),
        ("Desktop Metal", "company", {"status": "failed", "sector": "3D Printing", "country": "US"}),
        ("Veev", "company", {"status": "failed", "sector": "Construction Tech", "country": "US"}),
        ("Arrival", "company", {"status": "failed", "sector": "EV Manufacturing", "country": "UK"}),
        ("Lordstown Motors", "company", {"status": "failed", "sector": "EV Manufacturing", "country": "US"}),
        # Investors
        ("Sequoia Capital", "investor", {"type": "VC", "focus": "Technology"}),
        ("a16z", "investor", {"type": "VC", "focus": "Technology"}),
        ("Founders Fund", "investor", {"type": "VC", "focus": "Deep Tech"}),
        ("Tiger Global", "investor", {"type": "VC", "focus": "Growth"}),
        ("Goldman Sachs", "investor", {"type": "Investment Bank", "focus": "Various"}),
        ("SoftBank", "investor", {"type": "VC/PE", "focus": "Technology"}),
        ("ARK Invest", "investor", {"type": "ETF", "focus": "Innovation"}),
        ("NationalGrid", "investor", {"type": "Strategic", "focus": "Energy"}),
        ("ExxonMobil Ventures", "investor", {"type": "Strategic", "focus": "Energy"}),
        # Technologies
        ("Lithium-ion Battery", "technology", {"category": "Energy Storage"}),
        ("Solid State Battery", "technology", {"category": "Energy Storage"}),
        ("Smart PIGging", "technology", {"category": "Pipeline Inspection"}),
        ("Digital Twin", "technology", {"category": "Simulation"}),
        ("CVD Silicon Carbide", "technology", {"category": "Semiconductor Materials"}),
        ("GaN Power Devices", "technology", {"category": "Semiconductor Materials"}),
        ("Additive Manufacturing", "technology", {"category": "3D Printing"}),
        ("Robotic Process Automation", "technology", {"category": "Automation"}),
        ("IIoT Sensors", "technology", {"category": "Industrial IoT"}),
        ("Machine Vision", "technology", {"category": "Computer Vision"}),
        # Sectors
        ("EV Manufacturing", "sector", {"trend": "growing", "us_revenue_billion": 85}),
        ("Battery Manufacturing", "sector", {"trend": "growing", "us_revenue_billion": 45}),
        ("Semiconductor Manufacturing", "sector", {"trend": "growing", "us_revenue_billion": 120}),
        ("Solar Manufacturing", "sector", {"trend": "growing", "us_revenue_billion": 35}),
        ("3D Printing", "sector", {"trend": "stable", "us_revenue_billion": 18}),
        ("Robotics", "sector", {"trend": "growing", "us_revenue_billion": 55}),
        ("Pipeline Inspection", "sector", {"trend": "stable", "us_revenue_billion": 8}),
        # Geographic Regions
        ("Ohio", "geographic", {"type": "US State", "focus": "Manufacturing"}),
        ("Arizona", "geographic", {"type": "US State", "focus": "Semiconductors"}),
        ("Michigan", "geographic", {"type": "US State", "focus": "Auto/EV"}),
        ("Texas", "geographic", {"type": "US State", "focus": "Energy/Semiconductors"}),
        ("Rust Belt", "geographic", {"type": "Region", "focus": "Manufacturing Revitalization"}),
        ("Silicon Valley", "geographic", {"type": "Region", "focus": "Technology"}),
        ("Taiwan", "geographic", {"type": "Country", "focus": "Semiconductors"}),
        ("Europe", "geographic", {"type": "Continent", "focus": "Green Tech"}),
    ]

    for entity_data in kg_entities:
        name, etype, attrs = entity_data
        type_id = entity_type_id.get(etype, 1)

        import json
        cursor = conn.cursor()
        cursor.execute(
            """INSERT IGNORE INTO kg_entities
               (name, normalized_name, entity_type_id, attributes_json, mention_count)
               VALUES (%s, %s, %s, %s, 1)""",
            (name, name.lower(), type_id, json.dumps(attrs)),
        )
        cursor.close()

    _logger.info("Seeded %d knowledge graph entities", len(kg_entities))

    # Knowledge Graph Relationships
    kg_relationships = [
        # Company-Technology Relationships
        ("Northvolt", "produces", "Lithium-ion Battery"),
        ("Tesla", "produces", "Lithium-ion Battery"),
        ("Tesla", "uses", "GaN Power Devices"),
        ("Intel", "produces", "CVD Silicon Carbide"),
        ("TSMC", "produces", "CVD Silicon Carbide"),
        ("Desktop Metal", "uses", "Additive Manufacturing"),
        ("Rivian", "produces", "EV Manufacturing"),
        # Company-Sector Relationships
        ("Northvolt", "operates_in", "Battery Manufacturing"),
        ("Tesla", "operates_in", "EV Manufacturing"),
        ("Intel", "operates_in", "Semiconductor Manufacturing"),
        ("TSMC", "operates_in", "Semiconductor Manufacturing"),
        ("First Solar", "operates_in", "Solar Manufacturing"),
        # Investor-Company Relationships
        ("SoftBank", "invested_in", "Northvolt"),
        ("Goldman Sachs", "invested_in", "Northvolt"),
        ("Sequoia Capital", "invested_in", "Rivian"),
        ("ARK Invest", "invested_in", "Tesla"),
        # Geographic-Sector Relationships
        ("Ohio", "hosts", "EV Manufacturing"),
        ("Ohio", "hosts", "Battery Manufacturing"),
        ("Arizona", "hosts", "Semiconductor Manufacturing"),
        ("Michigan", "hosts", "EV Manufacturing"),
        ("Texas", "hosts", "Semiconductor Manufacturing"),
        # Failure Patterns
        ("Northvolt", "failed_due_to", "capital_intensity"),
        ("Katerra", "failed_due_to", "capital_intensity"),
        ("Desktop Metal", "failed_due_to", "spac_overvaluation"),
        ("Arrival", "failed_due_to", "spac_overvaluation"),
        ("Veev", "failed_due_to", "supply_chain"),
        # Sector Relationships
        ("EV Manufacturing", "requires", "Battery Manufacturing"),
        ("Battery Manufacturing", "enables", "EV Manufacturing"),
        ("Semiconductor Manufacturing", "enables", "EV Manufacturing"),
        # Technology Enablers
        ("Lithium-ion Battery", "enables", "EV Manufacturing"),
        ("Solid State Battery", "will_enable", "EV Manufacturing"),
        ("Smart PIGging", "enables", "Pipeline Inspection"),
        ("Digital Twin", "enables", "Manufacturing"),
        ("IIoT Sensors", "enables", "Robotics"),
    ]

    # Get entity IDs for relationship building
    entity_id_map = {}
    cursor = conn.cursor()
    cursor.execute("SELECT id, name FROM kg_entities")
    for row in cursor.fetchall():
        entity_id_map[row["name"]] = row["id"]
    cursor.close()

    for source, rel_type, target in kg_relationships:
        source_id = entity_id_map.get(source)
        target_id = entity_id_map.get(target)

        if source_id and target_id:
            cursor = conn.cursor()
            cursor.execute(
                """INSERT IGNORE INTO kg_relationships
                   (source_entity_id, target_entity_id, relationship_type, weight)
                   VALUES (%s, %s, %s, 1.0)""",
                (source_id, target_id, rel_type),
            )
            cursor.close()

    _logger.info("Seeded %d knowledge graph relationships", len(kg_relationships))

    conn.commit()

    # Verify
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) as cnt FROM failed_startups")
    startup_count = cursor.fetchone()["cnt"]
    cursor.close()
    _logger.info("Database now contains %d startup records", startup_count)
    conn.close()


if __name__ == "__main__":
    seed()
