"""Qdrant vector database client for semantic search.

Provides vector similarity search over raw signals using Qdrant.
Embeddings are generated by all-MiniLM-L6-v2 (384-dim) and stored with
metadata payloads for filtering and retrieval.

Design choices:
    - Single collection "startup_signals" for all signal types
    - Cosine distance (L2-normalized embeddings)
    - HNSW index for fast approximate nearest neighbor search
    - Graceful degradation: if Qdrant unavailable, returns empty results
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

_logger = logging.getLogger(__name__)


@dataclass
class SearchResult:
    """Single vector search result from Qdrant."""

    id: str
    score: float  # Cosine similarity (0-1)
    payload: dict = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "score": round(self.score, 4),
            "payload": self.payload,
        }


class VectorStore:
    """Qdrant vector database client for semantic search.

    Collection design:
        - Name: "startup_signals"
        - Dimension: 384 (all-MiniLM-L6-v2)
        - Distance: Cosine
        - Index: HNSW (m=16, ef_construct=200)

    Config options:
        url: Qdrant HTTP API (default: http://localhost:6333)
        collection_name: collection name (default: startup_signals)
        embedding_dim: vector dimension (default: 384)
        batch_size: batch upsert size (default: 100)
    """

    def __init__(self, config: dict | None = None):
        self._config = config or {}
        self._url = self._config.get("url", "http://localhost:6333")
        self._collection = self._config.get("collection_name", "startup_signals")
        self._embedding_dim = self._config.get("embedding_dim", 384)
        self._batch_size = self._config.get("batch_size", 100)
        self._client = None
        self._connected = False

    def connect(self) -> bool:
        """Initialize connection and create collection if needed.

        Returns True if successful, False if Qdrant is unavailable.
        """
        try:
            from qdrant_client import QdrantClient
            from qdrant_client.http import models

            self._client = QdrantClient(url=self._url)

            # Check if collection exists, create if not
            collections = self._client.get_collections().collections
            names = {c.name for c in collections}

            if self._collection not in names:
                self._client.create_collection(
                    collection_name=self._collection,
                    vectors_config=models.VectorParams(
                        size=self._embedding_dim,
                        distance=models.Distance.COSINE,
                    ),
                    hnsw_config=models.HnswConfigDiff(
                        m=16,
                        ef_construct=200,
                    ),
                )
                _logger.info(
                    "VectorStore: created collection '%s' (dim=%d)",
                    self._collection, self._embedding_dim,
                )

            self._connected = True
            _logger.info("VectorStore: connected to Qdrant at %s", self._url)
            return True

        except ImportError:
            _logger.warning("VectorStore: qdrant-client not installed")
            return False
        except Exception as e:
            _logger.warning("VectorStore: cannot connect to Qdrant: %s", e)
            return False

    @property
    def is_connected(self) -> bool:
        return self._connected and self._client is not None

    def upsert(self, point_id: str, vector: list[float], payload: dict) -> bool:
        """Upsert a single vector with payload.

        Args:
            point_id: Unique point identifier.
            vector: Embedding vector (384-dim).
            payload: Metadata dictionary.
        """
        if not self.is_connected:
            return False

        try:
            from qdrant_client.http import models

            self._client.upsert(
                collection_name=self._collection,
                points=[
                    models.PointStruct(
                        id=point_id,
                        vector=vector,
                        payload=payload,
                    )
                ],
            )
            return True
        except Exception as e:
            _logger.warning("VectorStore: upsert failed: %s", e)
            return False

    def upsert_batch(
        self, ids: list[str], vectors: list[list[float]], payloads: list[dict],
    ) -> int:
        """Batch upsert vectors.

        Args:
            ids: List of point IDs.
            vectors: List of embedding vectors.
            payloads: List of metadata dicts.

        Returns:
            Number of successfully upserted points.
        """
        if not self.is_connected:
            return 0

        try:
            from qdrant_client.http import models

            points = [
                models.PointStruct(id=pid, vector=vec, payload=payload)
                for pid, vec, payload in zip(ids, vectors, payloads)
            ]

            # Upsert in batches
            upserted = 0
            for i in range(0, len(points), self._batch_size):
                batch = points[i : i + self._batch_size]
                self._client.upsert(
                    collection_name=self._collection, points=batch,
                )
                upserted += len(batch)

            return upserted
        except Exception as e:
            _logger.warning("VectorStore: batch upsert failed: %s", e)
            return 0

    def search(
        self,
        query_vector: list[float],
        limit: int = 20,
        filters: dict[str, str] | None = None,
    ) -> list[SearchResult]:
        """Semantic search by query vector.

        Args:
            query_vector: 384-dim embedding of the query text.
            limit: Max results.
            filters: Optional filter conditions {"entity_type": "company"}.

        Returns:
            List of SearchResult sorted by score descending.
        """
        if not self.is_connected:
            return []

        try:
            from qdrant_client.http import models

            # Build Qdrant filter from dict
            qdrant_filter = None
            if filters:
                conditions = []
                for key, value in filters.items():
                    conditions.append(
                        models.FieldCondition(
                            key=key, match=models.MatchValue(value=value),
                        )
                    )
                qdrant_filter = models.Filter(must=conditions)

            results = self._client.search(
                collection_name=self._collection,
                query_vector=query_vector,
                limit=limit,
                query_filter=qdrant_filter,
            )

            return [
                SearchResult(
                    id=str(r.id),
                    score=r.score,
                    payload=r.payload or {},
                )
                for r in results
            ]
        except Exception as e:
            _logger.warning("VectorStore: search failed: %s", e)
            return []

    def search_by_text(
        self,
        query_text: str,
        embedding_generator,
        limit: int = 20,
        filters: dict[str, str] | None = None,
    ) -> list[SearchResult]:
        """Convenience: embed query text and search.

        Args:
            query_text: Natural language query.
            embedding_generator: EmbeddingGenerator instance.
            limit: Max results.
            filters: Optional filter conditions.

        Returns:
            List of SearchResult.
        """
        query_vector = embedding_generator.embed_text(query_text)
        return self.search(query_vector, limit=limit, filters=filters)

    def delete(self, ids: list[str]) -> bool:
        """Delete vectors by IDs."""
        if not self.is_connected:
            return False
        try:
            self._client.delete(
                collection_name=self._collection,
                points_selector={"ids": ids},
            )
            return True
        except Exception as e:
            _logger.warning("VectorStore: delete failed: %s", e)
            return False

    def count(self) -> int:
        """Return total vector count in collection."""
        if not self.is_connected:
            return 0
        try:
            info = self._client.get_collection(self._collection)
            return info.points_count or 0
        except Exception:
            return 0
