#!/usr/bin/env python3
"""
Agile Workflow CLI — Sprint management tool

Usage:
    python scripts/agile_cli.py planning                # Sprint planning template
    python scripts/agile_cli.py standup [--ci]          # Daily standup template
    python scripts/agile_cli.py review [--sprint N]     # Sprint review report
    python scripts/agile_cli.py retrospective           # Retro template
    python scripts/agile_cli.py backlog                 # Show product backlog
    python scripts/agile_cli.py metrics                 # Velocity & metrics
    python scripts/agile_cli.py create-task             # Interactive task creation
    python scripts/agile_cli.py move-task T-001 done    # Move task to column
    python scripts/agile_cli.py burndown                # Show burndown chart
    python scripts/agile_cli.py labels                  # Create GitHub labels
"""

import sys
import re
import subprocess
from pathlib import Path
from datetime import datetime, timedelta

PROJECT_ROOT = Path(__file__).parent.parent
SPRINTS_DIR = PROJECT_ROOT / "docs" / "sprints"
STANDUPS_DIR = SPRINTS_DIR / "standups"
REVIEWS_DIR = SPRINTS_DIR / "reviews"
RETROS_DIR = SPRINTS_DIR / "retros"
BACKLOG_FILE = SPRINTS_DIR / "backlog.md"
VELOCITY_FILE = SPRINTS_DIR / "velocity.md"
TRACKER_FILE = SPRINTS_DIR / "sprint-tracker.yaml"

# Ensure dirs exist
for d in [STANDUPS_DIR, REVIEWS_DIR, RETROS_DIR]:
    d.mkdir(parents=True, exist_ok=True)


# ANSI colors
class C:
    RED = "\033[91m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    BLUE = "\033[94m"
    MAGENTA = "\033[95m"
    CYAN = "\033[96m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RESET = "\033[0m"


def parse_tracker():
    """Parse sprint-tracker.yaml."""
    try:
        import yaml

        with open(TRACKER_FILE) as f:
            return yaml.safe_load(f.read())
    except ImportError:
        print(
            f"{C.YELLOW}Warning: PyYAML not installed. Install with: pip install pyyaml{C.RESET}"
        )
        return {}
    except FileNotFoundError:
        print(f"{C.RED}Error: {TRACKER_FILE} not found{C.RESET}")
        return {}


def get_current_sprint():
    """Get current sprint number."""
    data = parse_tracker()
    return data.get("current_sprint", 1)


def get_test_count():
    """Run pytest --co to count tests."""
    try:
        result = subprocess.run(
            ["python", "-m", "pytest", "tests/", "--co", "-q"],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=str(PROJECT_ROOT),
        )
        match = re.search(r"(\d+) tests? selected", result.output)
        if match:
            return int(match.group(1))
    except Exception:
        pass
    return "?"


# ── Sprint Planning ─────────────────────────────────────
def cmd_planning():
    """Generate sprint planning template."""
    sprint = get_current_sprint()
    data = parse_tracker()
    sprints = data.get("sprints", {})
    sprint_key = f"sprint_{sprint}"
    sprint_info = sprints.get(sprint_key, {})

    today = datetime.now().strftime("%Y-%m-%d")
    sprint_end = (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%d")

    # Get previous sprint velocity
    prev_sprint = sprint - 1
    prev_key = f"sprint_{prev_sprint}"
    prev_velocity = "N/A"
    if prev_sprint > 0 and prev_key in sprints:
        prev_data = sprints[prev_key]
        prev_tasks = prev_data.get("tasks", {})
        done = sum(1 for t in prev_tasks.values() if t.get("status") == "DONE")
        prev_velocity = f"{done} tasks"

    template = f"""# 🗓️ Sprint {sprint} Planning — {today}

## Sprint Goal
> {sprint_info.get('theme', 'TBD')}

## Duration: {today} → {sprint_end} (2 weeks)

## Previous Sprint Velocity
- Sprint {prev_sprint}: {prev_velocity}

## Capacity
- Available hours: ___
- Team members: ___
- Available capacity: ___ hours

## Stories / Tasks Selected

| ID | Story/Task | Points | Priority | Assignee | Notes |
|---|---|---|---|---|---|
| T-___ | | | P_ | | |

## Sprint Goal Checklist
- [ ] Goal is clear and measurable
- [ ] All stories have acceptance criteria
- [ ] All stories are estimated
- [ ] Capacity matches commitment
- [ ] Dependencies identified
- [ ] No external blockers

## Risks
| Risk | Impact | Mitigation |
|---|---|---|
| | | |

## Commitment
- Story points committed: ___
- Tasks committed: ___
- Confidence level: ___/5

---
*Generated by agile_cli.py on {today}*
"""
    output_file = SPRINTS_DIR / f"sprint-{sprint}-planning-{today}.md"
    output_file.write_text(template)
    print(f"{C.GREEN}✅ Sprint planning template created: {output_file}{C.RESET}")
    print(f"\n{C.BOLD}Sprint {sprint} Goal: {sprint_info.get('theme', 'TBD')}{C.RESET}")
    print(f"Duration: {today} → {sprint_end}")
    print("\nNext steps:")
    print("  1. Fill in stories/tasks")
    print("  2. Estimate story points")
    print("  3. Verify capacity")
    print("  4. Update sprint-tracker.yaml")
    print(
        f"  5. Commit: git add -A && git commit -m 'chore(sprint): plan sprint {sprint}'"
    )


# ── Daily Standup ───────────────────────────────────────
def cmd_standup(ci_mode=False):
    """Generate daily standup template."""
    today = datetime.now().strftime("%Y-%m-%d")
    sprint = get_current_sprint()
    data = parse_tracker()
    sprint_key = f"sprint_{sprint}"
    sprint_data = data.get("sprints", {}).get(sprint_key, {})
    tasks = sprint_data.get("tasks", {})

    # Categorize tasks
    done_tasks = [(tid, t) for tid, t in tasks.items() if t.get("status") == "DONE"]
    pending_tasks = [(tid, t) for tid, t in tasks.items() if t.get("status") != "DONE"]
    total = len(tasks)
    done_count = len(done_tasks)
    pct = int(done_count / total * 100) if total > 0 else 0

    # Check for recently completed (last 24h)
    yesterday_tasks = []
    for tid, t in done_tasks:
        completed = t.get("completed_at", "")
        if completed:
            try:
                completed_date = datetime.fromisoformat(
                    completed.replace("Z", "+00:00")
                ).date()
                if (datetime.now().date() - completed_date).days <= 1:
                    yesterday_tasks.append(f"  ✅ {tid}: {t.get('description', '')}")
            except (ValueError, TypeError):
                pass

    template = f"""# 🏃 Daily Standup — {today}

## Sprint {sprint}: {sprint_data.get('name', 'TBD')}
Progress: {done_count}/{total} tasks ({pct}%)

### What did I complete yesterday?
{chr(10).join(yesterday_tasks) if yesterday_tasks else "  _(No tasks completed yesterday)_"}

### What am I working on today?
- [ ]

### Any blockers?
-

### Quick Metrics
- Sprint progress: {pct}%
- Tasks remaining: {total - done_count}
- Sprint end: _(calculate from planning date)_

---
*Generated by agile_cli.py — {datetime.now().strftime('%H:%M:%S')}*
"""

    output_file = STANDUPS_DIR / f"{today}.md"
    output_file.write_text(template)

    if ci_mode:
        # CI mode: print summary for GitHub Actions
        print(f"Sprint {sprint}: {done_count}/{total} tasks ({pct}%)")
        if yesterday_tasks:
            print(f"Recently completed: {len(yesterday_tasks)} tasks")
        if pending_tasks:
            print(f"Remaining: {len(pending_tasks)} tasks")
    else:
        print(f"{C.GREEN}✅ Standup created: {output_file}{C.RESET}")
        print(f"\n{C.BOLD}Sprint {sprint} Status:{C.RESET}")
        print(f"  Progress: {done_count}/{total} ({pct}%)")

        # Progress bar
        bar_len = 30
        filled = int(bar_len * pct / 100)
        bar = f"{C.GREEN}{'█' * filled}{C.DIM}{'░' * (bar_len - filled)}{C.RESET}"
        print(f"  [{bar}] {pct}%")

        if yesterday_tasks:
            print(f"\n  {C.BOLD}Recently completed:{C.RESET}")
            for t in yesterday_tasks:
                print(f"    {t}")

        if pending_tasks[:5]:
            print(f"\n  {C.BOLD}Up next:{C.RESET}")
            for tid, t in pending_tasks[:5]:
                print(
                    f"    🔲 {tid}: {t.get('description', '')} ({t.get('effort', '?')})"
                )

        print(
            f"\n{C.DIM}Edit the standup file, then close the issue when done.{C.RESET}"
        )


# ── Sprint Review ───────────────────────────────────────
def cmd_review(sprint_num=None):
    """Generate sprint review report."""
    sprint = sprint_num or get_current_sprint()
    data = parse_tracker()
    sprint_key = f"sprint_{sprint}"
    sprint_data = data.get("sprints", {}).get(sprint_key, {})

    if not sprint_data:
        print(f"{C.RED}No data found for Sprint {sprint}{C.RESET}")
        return

    tasks = sprint_data.get("tasks", {})
    objectives = sprint_data.get("objectives", {})
    deliverables = sprint_data.get("deliverables", {})
    sprint_data.get("acceptance_criteria", {})
    metrics = sprint_data.get("metrics", {})
    dod = sprint_data.get("definition_of_done", {})

    done_tasks = sum(1 for t in tasks.values() if t.get("status") == "DONE")
    total_tasks = len(tasks)

    report = f"""# 📊 Sprint {sprint} Review — {datetime.now().strftime('%Y-%m-%d')}

## Sprint: {sprint_data.get('name', 'TBD')}
## Theme: {sprint_data.get('theme', 'TBD')}

---

## Summary

| Metric | Count |
|---|---|
| Total Tasks | {total_tasks} |
| Completed | {done_tasks} |
| Remaining | {total_tasks - done_tasks} |
| Completion | {sprint_data.get('completion_pct', 0)}% |

## ✅ Completed Tasks

"""
    for tid, t in sorted(tasks.items()):
        if t.get("status") == "DONE":
            report += (
                f"- ✅ {tid}: {t.get('description', '')} ({t.get('effort', '?')})\n"
            )

    report += """
## 🔲 Incomplete Tasks

"""
    for tid, t in sorted(tasks.items()):
        if t.get("status") != "DONE":
            report += f"- 🔲 {tid}: {t.get('description', '')} ({t.get('effort', '?')}) — {t.get('status', 'TODO')}\n"

    report += """
## Objectives

"""
    for oid, o in objectives.items():
        icon = "✅" if o.get("status") in ("DONE", "MET") else "🔲"
        report += (
            f"- {icon} {oid}: {o.get('description', '')} — {o.get('status', 'TODO')}\n"
        )

    report += """
## Deliverables

"""
    for did, d in deliverables.items():
        icon = "✅" if d.get("status") == "DONE" else "🔲"
        report += (
            f"- {icon} {did}: {d.get('artifact', '')} — {d.get('status', 'TODO')}\n"
        )

    report += """
## Metrics

| Metric | Target | Actual | Met? |
|---|---|---|---|
"""
    for mid, m in metrics.items():
        met = "✅" if m.get("met", False) else "❌"
        report += (
            f"| {mid} | {m.get('target', '?')} | {m.get('actual', '?')} | {met} |\n"
        )

    report += """
## Definition of Done

"""
    for key, val in dod.items():
        icon = "✅" if val else "❌"
        label = key.replace("_", " ").title()
        report += f"- {icon} {label}\n"

    report += f"""
---

## Demo Items
<!-- List features to demo -->

## Feedback
<!-- Collect feedback from stakeholders -->

## Action Items
<!-- Carry forward to next sprint -->

---
*Generated by agile_cli.py on {datetime.now().isoformat()}*
"""

    output_file = (
        REVIEWS_DIR / f"sprint-{sprint}-review-{datetime.now().strftime('%Y-%m-%d')}.md"
    )
    output_file.write_text(report)
    print(f"{C.GREEN}✅ Sprint review created: {output_file}{C.RESET}")


# ── Retrospective ───────────────────────────────────────
def cmd_retrospective():
    """Generate retrospective template."""
    sprint = get_current_sprint()
    today = datetime.now().strftime("%Y-%m-%d")

    template = f"""# 🔄 Sprint {sprint} Retrospective — {today}

## Format: Keep / Problem / Action (KPA)

### ✅ KEEP — What went well?
<!-- Things to continue doing -->
-

### ❌ PROBLEM — What didn't go well?
<!-- Things to stop or change -->
-

### 🎯 ACTION — What will we improve?
<!-- Specific, measurable improvements for next sprint -->
| Action | Owner | Due | Status |
|---|---|---|---|
| | | | |

---

## Team Health Check (1-5)

| Dimension | Score (1-5) | Notes |
|---|---|---|
| Velocity | ___ | |
| Quality | ___ | |
| Communication | ___ | |
| Morale | ___ | |
| Process | ___ | |

## Metrics Review
- Story points planned: ___
- Story points completed: ___
- Carry-over tasks: ___
- Bugs found: ___
- PR review time: ___

## Carried to Next Sprint
<!-- Tasks that didn't get done -->
-

---
*Generated by agile_cli.py on {datetime.now().isoformat()}*
"""

    output_file = RETROS_DIR / f"sprint-{sprint}-retro-{today}.md"
    output_file.write_text(template)
    print(f"{C.GREEN}✅ Retrospective created: {output_file}{C.RESET}")
    print(f"\n{C.BOLD}Run after sprint review.{C.RESET}")
    print(f"Focus on actionable improvements for Sprint {sprint + 1}.")


# ── Backlog ─────────────────────────────────────────────
def cmd_backlog():
    """Show product backlog."""
    if BACKLOG_FILE.exists():
        print(BACKLOG_FILE.read_text())
    else:
        # Generate from tracker
        data = parse_tracker()
        sprints = data.get("sprints", {})

        backlog = f"""# 📋 Product Backlog

> Auto-generated from sprint-tracker.yaml on {datetime.now().strftime('%Y-%m-%d')}

## Summary

"""
        for i in range(1, 9):
            sprint_key = f"sprint_{i}"
            sprint = sprints.get(sprint_key, {})
            name = sprint.get("name", f"Sprint {i}")
            status = sprint.get("status", "NOT STARTED")
            pct = sprint.get("completion_pct", 0)
            tasks = sprint.get("tasks", {})
            sum(1 for t in tasks.values() if t.get("status") == "DONE")
            len(tasks)

            status_icon = {
                "COMPLETE": "✅",
                "BLOCKED": "🔒",
                "IN_PROGRESS": "⏳",
            }.get(status, "🔲")

            backlog += f"### {status_icon} Sprint {i}: {name} ({status} — {pct}%)\n"
            if tasks:
                for tid, t in sorted(tasks.items()):
                    icon = "✅" if t.get("status") == "DONE" else "🔲"
                    backlog += f"- {icon} {tid}: {t.get('description', '')} ({t.get('effort', '?')})\n"
            backlog += "\n"

        BACKLOG_FILE.write_text(backlog)
        print(backlog)


# ── Metrics / Velocity ─────────────────────────────────
def cmd_metrics():
    """Show velocity and metrics."""
    data = parse_tracker()
    sprints = data.get("sprints", {})
    current = data.get("current_sprint", 1)

    print(f"\n{C.BOLD}{'='*60}{C.RESET}")
    print(f"{C.BOLD}  📊 VELOCITY & METRICS{C.RESET}")
    print(f"{'='*60}{C.RESET}\n")

    print(f"  {'SPRINT':<10} {'STATUS':<15} {'TASKS':<15} {'COMPLETION'}")
    print(f"  {'─'*10} {'─'*15} {'─'*15} {'─'*12}")

    total_done = 0
    total_tasks = 0

    for i in range(1, 9):
        sprint_key = f"sprint_{i}"
        sprint = sprints.get(sprint_key, {})
        tasks = sprint.get("tasks", {})
        done = sum(1 for t in tasks.values() if t.get("status") == "DONE")
        total = len(tasks)
        total_done += done
        total_tasks += total
        status = sprint.get("status", "NOT STARTED")
        pct = sprint.get("completion_pct", 0)

        marker = " ◀" if i == current else ""
        status_color = {
            "COMPLETE": C.GREEN,
            "BLOCKED": C.RED,
            "IN_PROGRESS": C.YELLOW,
        }.get(status, C.DIM)

        print(
            f"  {i:<10} {status_color}{status:<15}{C.RESET} {done}/{total:<13} {pct}%{marker}"
        )

    print(
        f"\n  {C.BOLD}Total: {total_done}/{total_tasks} tasks across 8 sprints{C.RESET}"
    )

    # Test count
    test_count = get_test_count()
    print(f"  {C.BOLD}Tests: {test_count}{C.RESET}")

    print()


# ── Create Task ─────────────────────────────────────────
def cmd_create_task():
    """Interactive task creation."""
    sprint = get_current_sprint()
    data = parse_tracker()
    sprint_key = f"sprint_{sprint}"
    sprint_data = data.get("sprints", {}).get(sprint_key, {})
    tasks = sprint_data.get("tasks", {})

    # Find next task ID
    existing_ids = []
    for tid in tasks.keys():
        match = re.match(r"T-(\d+)", tid)
        if match:
            existing_ids.append(int(match.group(1)))

    next_id = max(existing_ids, default=0) + 1
    task_id = f"T-{next_id:03d}"

    print(f"\n{C.BOLD}Creating task {task_id} for Sprint {sprint}{C.RESET}\n")

    description = input("Description: ").strip()
    if not description:
        print(f"{C.RED}Cancelled.{C.RESET}")
        return

    effort = input("Effort estimate (e.g. 2h, 3 points): ").strip() or "TBD"
    priority = input("Priority (P0/P1/P2): ").strip() or "P1"

    # Build task entry
    task_entry = f"""  {task_id}: {{ description: "{description}", effort: "{effort}", status: "TODO", priority: "{priority}", created_at: "{datetime.now().isoformat()}" }}"""

    print(f"\n{C.BOLD}Task to add to sprint-tracker.yaml:{C.RESET}")
    print(task_entry)
    print(
        f"\n{C.DIM}Add this to the tasks section of sprint_{sprint} in {TRACKER_FILE}{C.RESET}"
    )

    # Also create a GitHub issue body suggestion
    issue_body = f"""## Task: {task_id}

**Description**: {description}
**Sprint**: {sprint}
**Priority**: {priority}
**Effort**: {effort}

### Acceptance Criteria
- [ ]

### Implementation Notes
<!-- Add technical details -->
"""
    print(f"\n{C.BOLD}GitHub Issue Body:{C.RESET}")
    print(issue_body)


# ── Move Task ───────────────────────────────────────────
def cmd_move_task(task_id, new_status):
    """Move a task to a new status column."""
    data = parse_tracker()
    sprint = get_current_sprint()
    sprint_key = f"sprint_{sprint}"
    sprint_data = data.get("sprints", {}).get(sprint_key, {})
    tasks = sprint_data.get("tasks", {})

    if task_id not in tasks:
        print(f"{C.RED}Task {task_id} not found in Sprint {sprint}{C.RESET}")
        return

    valid_statuses = ["TODO", "IN_PROGRESS", "IN_REVIEW", "DONE", "BLOCKED"]
    new_status = new_status.upper()
    if new_status not in valid_statuses:
        print(
            f"{C.RED}Invalid status: {new_status}. Use: {', '.join(valid_statuses)}{C.RESET}"
        )
        return

    old_status = tasks[task_id].get("status", "TODO")
    tasks[task_id]["status"] = new_status

    if new_status == "DONE":
        tasks[task_id]["completed_at"] = datetime.now().isoformat()

    # Write back
    try:
        import yaml

        data["sprints"][sprint_key]["tasks"][task_id] = tasks[task_id]
        with open(TRACKER_FILE, "w") as f:
            yaml.dump(
                data, f, default_flow_style=False, allow_unicode=True, sort_keys=False
            )
        print(f"{C.GREEN}✅ {task_id}: {old_status} → {new_status}{C.RESET}")
    except ImportError:
        print(f"{C.YELLOW}PyYAML required. Install: pip install pyyaml{C.RESET}")
        print(
            f"{C.DIM}Manually update {task_id} status to {new_status} in {TRACKER_FILE}{C.RESET}"
        )


# ── Burndown ────────────────────────────────────────────
def cmd_burndown():
    """Show ASCII burndown chart."""
    sprint = get_current_sprint()
    data = parse_tracker()
    sprint_key = f"sprint_{sprint}"
    sprint_data = data.get("sprints", {}).get(sprint_key, {})
    tasks = sprint_data.get("tasks", {})
    total = len(tasks)
    done = sum(1 for t in tasks.values() if t.get("status") == "DONE")
    remaining = total - done

    print(f"\n{C.BOLD}  📉 Sprint {sprint} Burndown{C.RESET}")
    print(f"  Total: {total} tasks | Done: {done} | Remaining: {remaining}\n")

    # Simple ASCII bar chart
    ideal_per_day = total / 14  # 14-day sprint

    print("  Day  Remaining  Chart")
    print(f"  {'─'*3}  {'─'*9}  {'─'*30}")

    # Show ideal line and actual
    for day in range(0, 15, 2):
        ideal = max(0, total - (ideal_per_day * day))
        bar_len = int(ideal / total * 30) if total > 0 else 0
        bar = f"{C.GREEN}{'█' * bar_len}{C.RESET}{C.DIM}{'░' * (30 - bar_len)}{C.RESET}"
        print(f"  {day:>3}  {int(ideal):>9}  {bar}")

    print(f"\n  {C.BOLD}Current: {remaining} remaining (Day ~?){C.RESET}")
    print()


# ── Create Labels ───────────────────────────────────────
def cmd_labels():
    """Print GitHub CLI commands to create labels."""
    labels = [
        ("sprint/1", "1D76DB", "Sprint 1 tasks"),
        ("sprint/2", "1D76DB", "Sprint 2 tasks"),
        ("sprint/3", "1D76DB", "Sprint 3 tasks"),
        ("sprint/4", "1D76DB", "Sprint 4 tasks"),
        ("sprint/5", "1D76DB", "Sprint 5 tasks"),
        ("sprint/6", "1D76DB", "Sprint 6 tasks"),
        ("sprint/7", "1D76DB", "Sprint 7 tasks"),
        ("sprint/8", "1D76DB", "Sprint 8 tasks"),
        ("priority/P0", "B60205", "Critical — ship blocker"),
        ("priority/P1", "D93F0B", "Important — sprint goal"),
        ("priority/P2", "FBCA04", "Nice to have"),
        ("type/story", "0E8A16", "User story"),
        ("type/task", "C2E0C6", "Technical task"),
        ("type/spike", "5319E7", "Research / exploration"),
        ("type/bug", "D73A4A", "Bug fix"),
        ("type/chore", "FEF2C0", "Maintenance"),
        ("status/blocked", "B60205", "Blocked by dependency"),
        ("status/in-progress", "FBCA04", "Currently being worked on"),
        ("standup", "C5DEF5", "Daily standup"),
        ("sprint-review", "C5DEF5", "Sprint review"),
        ("stale", "EDEDED", "Stale / inactive"),
        ("size/S", "28A745", "Small (<100 lines)"),
        ("size/M", "FBBD23", "Medium (100-400 lines)"),
        ("size/L", "F28A2E", "Large (400-1000 lines)"),
        ("size/XL", "E22B3D", "Extra Large (>1000 lines)"),
    ]

    print(f"\n{C.BOLD}# Create GitHub labels (run once):{C.RESET}\n")
    print("gh auth login  # if not already")
    print()

    for name, color, desc in labels:
        print(
            f'gh label create "{name}" --color "{color}" --description "{desc}" --force'
        )

    print(f"\n{C.DIM}# Or batch create:{C.RESET}")
    print(f"{C.DIM}# Copy the commands above and paste in terminal{C.RESET}")


# ── Help ────────────────────────────────────────────────
def cmd_help():
    """Show help."""
    print(f"""
{C.BOLD}🏃 Agile Workflow CLI{C.RESET}

{C.BOLD}Ceremonies:{C.RESET}
  planning              Sprint planning template
  standup [--ci]        Daily standup (use --ci for GitHub Actions)
  review [--sprint N]   Sprint review report (default: current sprint)
  retrospective         Retrospective template

{C.BOLD}Management:{C.RESET}
  backlog               Show product backlog
  metrics               Velocity & sprint metrics
  burndown              ASCII burndown chart
  create-task           Interactive task creation
  move-task ID STATUS   Move task (TODO/IN_PROGRESS/IN_REVIEW/DONE/BLOCKED)
  labels                Print GitHub label creation commands

{C.BOLD}Options:{C.RESET}
  --sprint N            Target specific sprint number
  --ci                  CI mode (concise output for GitHub Actions)
  -h, --help            Show this help

{C.BOLD}Examples:{C.RESET}
  python scripts/agile_cli.py planning
  python scripts/agile_cli.py standup
  python scripts/agile_cli.py review --sprint 2
  python scripts/agile_cli.py move-task T-001 done
  python scripts/agile_cli.py metrics
""")


# ── Main ────────────────────────────────────────────────
def main():
    args = sys.argv[1:]

    if not args or args[0] in ("-h", "--help"):
        cmd_help()
        return

    command = args[0]

    if command == "planning":
        cmd_planning()
    elif command == "standup":
        ci_mode = "--ci" in args
        cmd_standup(ci_mode=ci_mode)
    elif command == "review":
        sprint = None
        if "--sprint" in args:
            try:
                idx = args.index("--sprint")
                sprint = int(args[idx + 1])
            except (IndexError, ValueError):
                pass
        cmd_review(sprint)
    elif command == "retrospective":
        cmd_retrospective()
    elif command == "backlog":
        cmd_backlog()
    elif command == "metrics":
        cmd_metrics()
    elif command == "create-task":
        cmd_create_task()
    elif command == "move-task":
        if len(args) < 3:
            print(f"{C.RED}Usage: agile_cli.py move-task T-001 done{C.RESET}")
            return
        cmd_move_task(args[1], args[2])
    elif command == "burndown":
        cmd_burndown()
    elif command == "labels":
        cmd_labels()
    else:
        print(f"{C.RED}Unknown command: {command}{C.RESET}")
        cmd_help()


if __name__ == "__main__":
    main()
